[package]
name = "tex-cli"
version.workspace = true
edition.workspace = true

[[bin]]
name = "pdflatex"
path = "src/bin/pdflatex.rs"

[[bin]]
name = "xelatex"
path = "src/bin/xelatex.rs"

[[bin]]
name = "lualatex"
path = "src/bin/lualatex.rs"
[[bin]]
name = "tex-bibtex"
path = "src/bin/bibtex.rs"

[[bin]]
name = "texmk"
path = "src/bin/texmk.rs"

[[bin]]
name = "latexdiff"
path = "src/bin/latexdiff.rs"


[[bin]]
name = "ratex"
path = "src/bin/ratex.rs"
[dependencies]
dlmalloc = { workspace = true }
libc = { workspace = true }
tex-core = { path = "../tex-core" }
tex-kpse = { path = "../tex-kpse" }
tex-bibtex = { path = "../tex-bibtex" }
tex-ps = { path = "../tex-ps" }
