[package]
name = "tex-cli"
version.workspace = true
edition.workspace = true

[[bin]]
name = "pdflatex"
path = "src/bin/pdflatex.rs"

[[bin]]
name = "xelatex"
path = "src/bin/xelatex.rs"

[[bin]]
name = "lualatex"
path = "src/bin/lualatex.rs"
[[bin]]
name = "tex-bibtex"
path = "src/bin/bibtex.rs"

[[bin]]
name = "texmk"
path = "src/bin/texmk.rs"


[[bin]]
name = "ratex"
path = "src/bin/ratex.rs"
[dependencies]
mimalloc = "0.1.52"
libmimalloc-sys = "0.1.49"
libc = { workspace = true }
tex-core = { path = "../tex-core" }
tex-kpse = { path = "../tex-kpse" }
