[package]
name = "tex-cli"
version.workspace = true
edition.workspace = true

[[bin]]
name = "pdflatex"
path = "src/bin/pdflatex.rs"

[[bin]]
name = "tex-bibtex"
path = "src/bin/bibtex.rs"

[[bin]]
name = "texmk"
path = "src/bin/texmk.rs"

[[bin]]
name = "latexdiff"
path = "src/bin/latexdiff.rs"


[[bin]]
name = "texres"
path = "src/bin/texres.rs"
[dependencies]
dlmalloc = { workspace = true }
libc = { workspace = true }
tex-core = { path = "../tex-core" }
tex-kpse = { path = "../tex-kpse" }
tex-bibtex = { path = "../tex-bibtex" }
tex-ps = { path = "../tex-ps" }

[dev-dependencies]
flate2 = { workspace = true }
lopdf = { version = "0.44.0", default-features = false }
