local function s(g) return table.concat({g.lang, g.left, g.right, g.uchyph}, ",") end
local g = node.new("glyph")
P("default", s(g))
g.left = 2 P("left2", s(g))
g.right = 3 P("right3", s(g))
g.uchyph = 1 P("uchyph1", s(g))
g.lang = 5 P("lang5", s(g))
g.uchyph = 0 P("uchyph0", s(g))
g.left = 300 P("left300", s(g))
g.right = 0 P("right0", s(g))
g.lang = -1 P("lang-1", s(g))
g.lang = 40000 P("lang40000", s(g))
g.uchyph = 7 P("uchyph7", s(g))
g.uchyph = 0 P("uchyph0b", s(g))
g.left = -3 P("left-3", s(g))
g.uchyph = 2 P("uchyph2", s(g))
local h = node.new("glyph") h.uchyph = 1 P("fresh uchyph1", s(h))
h.left = 4 P("then left4", s(h))
local d = node.direct.new("glyph")
node.direct.setlang(d, 3) P("direct", node.direct.getlang(d))
node.direct.setfield(d, "left", 4) P("direct", node.direct.getfield(d, "left"), node.direct.getfield(d, "uchyph"))
