local D = {}
D.types = {[0]="hlist",[1]="vlist",[2]="rule",[3]="ins",[4]="mark",[5]="adjust",[6]="boundary",[7]="disc",[8]="whatsit",[9]="local_par",[10]="dir",[11]="math",[12]="glue",[13]="kern",[14]="penalty",[15]="unset",[16]="style",[17]="choice",[18]="noad",[19]="radical",[20]="fraction",[21]="accent",[22]="fence",[23]="math_char",[24]="sub_box",[25]="sub_mlist",[26]="math_text_char",[27]="delim",[28]="margin_kern",[29]="glyph",[30]="align_record",[31]="pseudo_file",[32]="pseudo_line",[33]="page_insert",[34]="split_insert",[35]="expr_stack",[36]="nested_list",[37]="span",[38]="attribute",[39]="glue_spec",[40]="attribute_list",[41]="temp",[42]="align_stack",[43]="movement_stack",[44]="if_stack",[45]="unhyphenated",[46]="hyphenated",[47]="delta",[48]="passive",[49]="shape"}
D.whatsits = {[0]="open",[1]="write",[2]="close",[3]="special",[4]="late_special",[7]="save_pos",[8]="late_lua",[9]="user_defined",[16]="pdf_literal",[17]="pdf_late_literal",[18]="pdf_refobj",[19]="pdf_annot",[20]="pdf_start_link",[21]="pdf_end_link",[22]="pdf_dest",[23]="pdf_action",[24]="pdf_thread",[25]="pdf_start_thread",[26]="pdf_end_thread",[27]="pdf_thread_data",[28]="pdf_link_data",[29]="pdf_colorstack",[30]="pdf_setmatrix",[31]="pdf_save",[32]="pdf_restore",[33]="pdf_link_state"}
D.fields = {}
D.fields[1] = {[-1]="prev",[0]="next",[1]="id",[2]="subtype",[3]="attr",[4]="width",[5]="depth",[6]="height",[7]="dir",[8]="shift",[9]="glue_order",[10]="glue_sign",[11]="glue_set",[12]="head"}
D.fields[2] = {[-1]="prev",[0]="next",[1]="id",[2]="subtype",[3]="attr",[4]="width",[5]="depth",[6]="height",[7]="dir",[8]="index",[9]="left",[10]="right"}
D.fields[3] = {[-1]="prev",[0]="next",[1]="id",[2]="subtype",[3]="attr",[4]="cost",[5]="depth",[6]="height",[7]="spec",[8]="head"}
D.fields[4] = {[-1]="prev",[0]="next",[1]="id",[2]="subtype",[3]="attr",[4]="class",[5]="mark"}
D.fields[5] = {[-1]="prev",[0]="next",[1]="id",[2]="subtype",[3]="attr",[4]="head"}
D.fields[6] = {[-1]="prev",[0]="next",[1]="id",[2]="subtype",[3]="attr",[4]="value"}
D.fields[7] = {[-1]="prev",[0]="next",[1]="id",[2]="subtype",[3]="attr",[4]="pre",[5]="post",[6]="replace",[7]="penalty"}
D.fields[9] = {[-1]="prev",[0]="next",[1]="id",[2]="subtype",[3]="attr",[4]="pen_inter",[5]="pen_broken",[6]="dir",[7]="box_left",[8]="box_left_width",[9]="box_right",[10]="box_right_width"}
D.fields[10] = {[-1]="prev",[0]="next",[1]="id",[2]="subtype",[3]="attr",[4]="dir",[5]="level"}
D.fields[11] = {[-1]="prev",[0]="next",[1]="id",[2]="subtype",[3]="attr",[4]="surround",[5]="width",[6]="stretch",[7]="shrink",[8]="stretch_order",[9]="shrink_order"}
D.fields[12] = {[-1]="prev",[0]="next",[1]="id",[2]="subtype",[3]="attr",[4]="leader",[5]="width",[6]="stretch",[7]="shrink",[8]="stretch_order",[9]="shrink_order"}
D.fields[13] = {[-1]="prev",[0]="next",[1]="id",[2]="subtype",[3]="attr",[4]="kern",[5]="expansion_factor"}
D.fields[14] = {[-1]="prev",[0]="next",[1]="id",[2]="subtype",[3]="attr",[4]="penalty"}
D.fields[15] = {[-1]="prev",[0]="next",[1]="id",[2]="subtype",[3]="attr",[4]="width",[5]="depth",[6]="height",[7]="dir",[8]="shrink",[9]="glue_order",[10]="glue_sign",[11]="stretch",[12]="span",[13]="head"}
D.fields[16] = {[-1]="prev",[0]="next",[1]="id",[2]="subtype",[3]="attr",[4]="style"}
D.fields[17] = {[-1]="prev",[0]="next",[1]="id",[2]="subtype",[3]="attr",[4]="display",[5]="text",[6]="script",[7]="scriptscript"}
D.fields[18] = {[-1]="prev",[0]="next",[1]="id",[2]="subtype",[3]="attr",[4]="nucleus",[5]="sub",[6]="sup"}
D.fields[19] = {[-1]="prev",[0]="next",[1]="id",[2]="subtype",[3]="attr",[4]="nucleus",[5]="sub",[6]="sup",[7]="left",[8]="degree",[9]="width",[10]="options"}
D.fields[20] = {[-1]="prev",[0]="next",[1]="id",[2]="subtype",[3]="attr",[4]="width",[5]="num",[6]="denom",[7]="left",[8]="right",[9]="middle",[10]="fam",[11]="options"}
D.fields[21] = {[-1]="prev",[0]="next",[1]="id",[2]="subtype",[3]="attr",[4]="nucleus",[5]="sub",[6]="sup",[7]="accent",[8]="bot_accent",[9]="top_accent",[10]="overlay_accent",[11]="fraction"}
D.fields[22] = {[-1]="prev",[0]="next",[1]="id",[2]="subtype",[3]="attr",[4]="delim",[5]="italic",[6]="height",[7]="depth",[8]="options",[9]="class"}
D.fields[23] = {[-1]="prev",[0]="next",[1]="id",[2]="subtype",[3]="attr",[4]="fam",[5]="char"}
D.fields[24] = {[-1]="prev",[0]="next",[1]="id",[2]="subtype",[3]="attr",[4]="head"}
D.fields[25] = {[-1]="prev",[0]="next",[1]="id",[2]="subtype",[3]="attr",[4]="head"}
D.fields[26] = {[-1]="prev",[0]="next",[1]="id",[2]="subtype",[3]="attr",[4]="fam",[5]="char"}
D.fields[27] = {[-1]="prev",[0]="next",[1]="id",[2]="subtype",[3]="attr",[4]="small_fam",[5]="small_char",[6]="large_fam",[7]="large_char"}
D.fields[28] = {[-1]="prev",[0]="next",[1]="id",[2]="subtype",[3]="attr",[4]="width",[5]="glyph"}
D.fields[29] = {[-1]="prev",[0]="next",[1]="id",[2]="subtype",[3]="attr",[4]="char",[5]="font",[6]="lang",[7]="left",[8]="right",[9]="uchyph",[10]="components",[11]="xoffset",[12]="yoffset",[13]="width",[14]="height",[15]="depth",[16]="expansion_factor",[17]="data"}
D.fields[30] = {[-1]="prev",[0]="next",[1]="id",[2]="subtype"}
D.fields[31] = {[-1]="prev",[0]="next",[1]="id",[2]="subtype"}
D.fields[32] = {[-1]="prev",[0]="next",[1]="id",[2]="subtype"}
D.fields[33] = {[-1]="prev",[0]="next",[1]="id",[2]="subtype",[3]="height",[4]="last_ins_ptr",[5]="best_ins_ptr",[6]="width",[7]="stretch",[8]="shrink",[9]="stretch_order",[10]="shrink_order"}
D.fields[34] = {[-1]="prev",[0]="next",[1]="id",[2]="subtype",[3]="height",[4]="last_ins_ptr",[5]="best_ins_ptr",[6]="broken_ptr",[7]="broken_ins"}
D.fields[35] = {[-1]="prev",[0]="next",[1]="id",[2]="subtype"}
D.fields[36] = {[-1]="prev",[0]="next",[1]="id",[2]="subtype"}
D.fields[37] = {[-1]="prev",[0]="next",[1]="id",[2]="subtype"}
D.fields[38] = {[0]="next",[1]="id",[2]="number",[3]="value"}
D.fields[39] = {[0]="next",[1]="id",[2]="width",[3]="stretch",[4]="shrink",[5]="stretch_order",[6]="shrink_order"}
D.fields[40] = {[0]="next",[1]="id"}
D.fields[41] = {[-1]="prev",[0]="next",[1]="id",[2]="subtype"}
D.fields[42] = {[-1]="prev",[0]="next",[1]="id",[2]="subtype"}
D.fields[43] = {[-1]="prev",[0]="next",[1]="id",[2]="subtype"}
D.fields[44] = {[-1]="prev",[0]="next",[1]="id",[2]="subtype"}
D.fields[45] = {[-1]="prev",[0]="next",[1]="id",[2]="subtype"}
D.fields[46] = {[-1]="prev",[0]="next",[1]="id",[2]="subtype"}
D.fields[47] = {[-1]="prev",[0]="next",[1]="id",[2]="subtype"}
D.fields[48] = {[-1]="prev",[0]="next",[1]="id",[2]="subtype"}
D.fields[49] = {[-1]="prev",[0]="next",[1]="id",[2]="subtype"}
D.fields[0] = {[-1]="prev",[0]="next",[1]="id",[2]="subtype",[3]="attr",[4]="width",[5]="depth",[6]="height",[7]="dir",[8]="shift",[9]="glue_order",[10]="glue_sign",[11]="glue_set",[12]="head"}
D.wfields = {}
D.wfields[1] = {[-1]="prev",[0]="next",[1]="id",[2]="subtype",[3]="attr",[4]="stream",[5]="data"}
D.wfields[2] = {[-1]="prev",[0]="next",[1]="id",[2]="subtype",[3]="attr",[4]="stream"}
D.wfields[3] = {[-1]="prev",[0]="next",[1]="id",[2]="subtype",[3]="attr",[4]="data"}
D.wfields[4] = {[-1]="prev",[0]="next",[1]="id",[2]="subtype",[3]="attr",[4]="data"}
D.wfields[7] = {[-1]="prev",[0]="next",[1]="id",[2]="subtype",[3]="attr"}
D.wfields[8] = {[-1]="prev",[0]="next",[1]="id",[2]="subtype",[3]="attr",[4]="reg",[5]="data",[6]="name",[7]="string"}
D.wfields[9] = {[-1]="prev",[0]="next",[1]="id",[2]="subtype",[3]="attr",[4]="user_id",[5]="type",[6]="value"}
D.wfields[16] = {[-1]="prev",[0]="next",[1]="id",[2]="subtype",[3]="attr",[4]="mode",[5]="data"}
D.wfields[17] = {[-1]="prev",[0]="next",[1]="id",[2]="subtype",[3]="attr",[4]="mode",[5]="data"}
D.wfields[18] = {[-1]="prev",[0]="next",[1]="id",[2]="subtype",[3]="attr",[4]="objnum"}
D.wfields[19] = {[-1]="prev",[0]="next",[1]="id",[2]="subtype",[3]="attr",[4]="width",[5]="depth",[6]="height",[7]="objnum",[8]="data"}
D.wfields[20] = {[-1]="prev",[0]="next",[1]="id",[2]="subtype",[3]="attr",[4]="width",[5]="depth",[6]="height",[7]="objnum",[8]="link_attr",[9]="action"}
D.wfields[21] = {[-1]="prev",[0]="next",[1]="id",[2]="subtype",[3]="attr"}
D.wfields[22] = {[-1]="prev",[0]="next",[1]="id",[2]="subtype",[3]="attr",[4]="width",[5]="depth",[6]="height",[7]="named_id",[8]="dest_id",[9]="dest_type",[10]="xyz_zoom",[11]="objnum"}
D.wfields[23] = {[-1]="prev",[0]="next",[1]="id",[2]="subtype",[3]="action_type",[4]="named_id",[5]="action_id",[6]="file",[7]="new_window",[8]="data",[9]="struct_id"}
D.wfields[24] = {[-1]="prev",[0]="next",[1]="id",[2]="subtype",[3]="attr",[4]="width",[5]="depth",[6]="height",[7]="named_id",[8]="thread_id",[9]="thread_attr"}
D.wfields[25] = {[-1]="prev",[0]="next",[1]="id",[2]="subtype",[3]="attr",[4]="width",[5]="depth",[6]="height",[7]="named_id",[8]="thread_id",[9]="thread_attr"}
D.wfields[26] = {[-1]="prev",[0]="next",[1]="id",[2]="subtype",[3]="attr"}
D.wfields[27] = {[-1]="prev",[0]="next",[1]="id",[2]="subtype"}
D.wfields[28] = {[-1]="prev",[0]="next",[1]="id",[2]="subtype"}
D.wfields[29] = {[-1]="prev",[0]="next",[1]="id",[2]="subtype",[3]="attr",[4]="stack",[5]="cmd",[6]="data"}
D.wfields[30] = {[-1]="prev",[0]="next",[1]="id",[2]="subtype",[3]="attr",[4]="data"}
D.wfields[31] = {[-1]="prev",[0]="next",[1]="id",[2]="subtype",[3]="attr"}
D.wfields[32] = {[-1]="prev",[0]="next",[1]="id",[2]="subtype",[3]="attr"}
D.wfields[0] = {[-1]="prev",[0]="next",[1]="id",[2]="subtype",[3]="attr",[4]="stream",[5]="name",[6]="area",[7]="ext"}
D.wfields[33] = {[-1]="prev",[0]="next",[1]="id",[2]="subtype",[3]="attr",[4]="value"}
D.subtypes = {}
D.subtypes["glyph"] = {[0]="unset",[1]="character",[2]="ligature",[4]="ghost",[8]="left",[16]="right"}
D.subtypes["glue"] = {[0]="userskip",[1]="lineskip",[2]="baselineskip",[3]="parskip",[4]="abovedisplayskip",[5]="belowdisplayskip",[6]="abovedisplayshortskip",[7]="belowdisplayshortskip",[8]="leftskip",[9]="rightskip",[10]="topskip",[11]="splittopskip",[12]="tabskip",[13]="spaceskip",[14]="xspaceskip",[15]="parfillskip",[16]="mathskip",[17]="thinmuskip",[18]="medmuskip",[19]="thickmuskip",[98]="conditionalmathskip",[99]="muglue",[100]="leaders",[101]="cleaders",[102]="xleaders",[103]="gleaders"}
D.subtypes["dir"] = {[0]="normal",[1]="cancel"}
D.subtypes["boundary"] = {[0]="cancel",[1]="user",[2]="protrusion",[3]="word"}
D.subtypes["penalty"] = {[0]="userpenalty",[1]="linebreakpenalty",[2]="linepenalty",[3]="wordpenalty",[4]="finalpenalty",[5]="noadpenalty",[6]="beforedisplaypenalty",[7]="afterdisplaypenalty",[8]="equationnumberpenalty"}
D.subtypes["kern"] = {[0]="fontkern",[1]="userkern",[2]="accentkern",[3]="italiccorrection"}
D.subtypes["rule"] = {[0]="normal",[1]="box",[2]="image",[3]="empty",[4]="user",[5]="over",[6]="under",[7]="fraction",[8]="radical",[9]="outline"}
D.subtypes["list"] = {[0]="unknown",[1]="line",[2]="box",[3]="indent",[4]="alignment",[5]="cell",[6]="equation",[7]="equationnumber",[8]="math",[9]="mathchar",[10]="hextensible",[11]="vextensible",[12]="hdelimiter",[13]="vdelimiter",[14]="overdelimiter",[15]="underdelimiter",[16]="numerator",[17]="denominator",[18]="limits",[19]="fraction",[20]="nucleus",[21]="sup",[22]="sub",[23]="degree",[24]="scripts",[25]="over",[26]="under",[27]="accent",[28]="radical"}
D.subtypes["hlist"] = {[0]="unknown",[1]="line",[2]="box",[3]="indent",[4]="alignment",[5]="cell",[6]="equation",[7]="equationnumber",[8]="math",[9]="mathchar",[10]="hextensible",[11]="vextensible",[12]="hdelimiter",[13]="vdelimiter",[14]="overdelimiter",[15]="underdelimiter",[16]="numerator",[17]="denominator",[18]="limits",[19]="fraction",[20]="nucleus",[21]="sup",[22]="sub",[23]="degree",[24]="scripts",[25]="over",[26]="under",[27]="accent",[28]="radical"}
D.subtypes["vlist"] = {[0]="unknown",[1]="line",[2]="box",[3]="indent",[4]="alignment",[5]="cell",[6]="equation",[7]="equationnumber",[8]="math",[9]="mathchar",[10]="hextensible",[11]="vextensible",[12]="hdelimiter",[13]="vdelimiter",[14]="overdelimiter",[15]="underdelimiter",[16]="numerator",[17]="denominator",[18]="limits",[19]="fraction",[20]="nucleus",[21]="sup",[22]="sub",[23]="degree",[24]="scripts",[25]="over",[26]="under",[27]="accent",[28]="radical"}
D.subtypes["adjust"] = {[0]="normal",[1]="pre"}
D.subtypes["disc"] = {[0]="discretionary",[1]="explicit",[2]="automatic",[3]="regular",[4]="first",[5]="second"}
D.subtypes["fill"] = {[0]="normal",[1]="fi",[2]="fil",[3]="fill",[4]="filll"}
D.subtypes["leader"] = {[100]="leaders",[101]="cleaders",[102]="xleaders",[103]="gleaders"}
D.subtypes["marginkern"] = {[0]="left",[1]="right"}
D.subtypes["math"] = {[0]="beginmath",[1]="endmath"}
D.subtypes["noad"] = {[0]="ord",[1]="opdisplaylimits",[2]="oplimits",[3]="opnolimits",[4]="bin",[5]="rel",[6]="open",[7]="close",[8]="punct",[9]="inner",[10]="under",[11]="over",[12]="vcenter"}
D.subtypes["radical"] = {[0]="radical",[1]="uradical",[2]="uroot",[3]="uunderdelimiter",[4]="uoverdelimiter",[5]="udelimiterunder",[6]="udelimiterover"}
D.subtypes["accent"] = {[0]="bothflexible",[1]="fixedtop",[2]="fixedbottom",[3]="fixedboth"}
D.subtypes["fence"] = {[0]="unset",[1]="left",[2]="middle",[3]="right",[4]="no"}
D.subtypes["pdf_destination"] = {[0]="xyz",[1]="fit",[2]="fith",[3]="fitv",[4]="fitb",[5]="fitbh",[6]="fitbv",[7]="fitr"}
D.subtypes["pdf_literal"] = {[0]="origin",[1]="page",[2]="always",[3]="raw",[4]="text",[5]="font",[6]="special"}
D.values = {}
D.values["dir"] = {[0]="TLT",[1]="TRT",[2]="LTL",[3]="RTT"}
D.values["direction"] = {[0]="TLT",[1]="TRT",[2]="LTL",[3]="RTT"}
D.values["glue"] = {[0]="normal",[1]="fi",[2]="fil",[3]="fill",[4]="filll"}
D.values["pdf_literal"] = {[0]="origin",[1]="page",[2]="always",[3]="raw",[4]="text",[5]="font",[6]="special"}
D.values["pdf_action"] = {[0]="page",[1]="goto",[2]="thread",[3]="user"}
D.values["pdf_window"] = {[0]="unset",[1]="new",[2]="nonew"}
D.values["color_stack"] = {[0]="set",[1]="push",[2]="pop",[3]="current"}
D.values["pagestate"] = {[0]="empty",[1]="box_there",[2]="inserts_only"}
return D
