// @generated by LuaNode/gen/gen.py from the luatex 1.24 node.types()/node.fields() probe; do not edit by hand.

#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum K { I, F, N, D, S, V }

pub struct TypeInfo { pub id: u8, pub name: &'static str, pub fields: &'static [(&'static str, K)], pub subtypes: &'static [(u16, &'static str)] }

pub const TYPES: &[TypeInfo] = &[
    TypeInfo { id: 0, name: "hlist", fields: &[("width", K::I), ("depth", K::I), ("height", K::I), ("dir", K::D), ("shift", K::I), ("glue_order", K::I), ("glue_sign", K::I), ("glue_set", K::F), ("head", K::N)], subtypes: &[(0, "unknown"), (1, "line"), (2, "box"), (3, "indent"), (4, "alignment"), (5, "cell"), (6, "equation"), (7, "equationnumber"), (8, "math"), (9, "mathchar"), (10, "hextensible"), (11, "vextensible"), (12, "hdelimiter"), (13, "vdelimiter"), (14, "overdelimiter"), (15, "underdelimiter"), (16, "numerator"), (17, "denominator"), (18, "limits"), (19, "fraction"), (20, "nucleus"), (21, "sup"), (22, "sub"), (23, "degree"), (24, "scripts"), (25, "over"), (26, "under"), (27, "accent"), (28, "radical")] },
    TypeInfo { id: 1, name: "vlist", fields: &[("width", K::I), ("depth", K::I), ("height", K::I), ("dir", K::D), ("shift", K::I), ("glue_order", K::I), ("glue_sign", K::I), ("glue_set", K::F), ("head", K::N)], subtypes: &[(0, "unknown"), (1, "line"), (2, "box"), (3, "indent"), (4, "alignment"), (5, "cell"), (6, "equation"), (7, "equationnumber"), (8, "math"), (9, "mathchar"), (10, "hextensible"), (11, "vextensible"), (12, "hdelimiter"), (13, "vdelimiter"), (14, "overdelimiter"), (15, "underdelimiter"), (16, "numerator"), (17, "denominator"), (18, "limits"), (19, "fraction"), (20, "nucleus"), (21, "sup"), (22, "sub"), (23, "degree"), (24, "scripts"), (25, "over"), (26, "under"), (27, "accent"), (28, "radical")] },
    TypeInfo { id: 2, name: "rule", fields: &[("width", K::I), ("depth", K::I), ("height", K::I), ("dir", K::D), ("index", K::I), ("left", K::I), ("right", K::I)], subtypes: &[(0, "normal"), (1, "box"), (2, "image"), (3, "empty"), (4, "user"), (5, "over"), (6, "under"), (7, "fraction"), (8, "radical"), (9, "outline")] },
    TypeInfo { id: 3, name: "ins", fields: &[("cost", K::I), ("depth", K::I), ("height", K::I), ("spec", K::N), ("head", K::N)], subtypes: &[] },
    TypeInfo { id: 4, name: "mark", fields: &[("class", K::I), ("mark", K::S)], subtypes: &[] },
    TypeInfo { id: 5, name: "adjust", fields: &[("head", K::N)], subtypes: &[(0, "normal"), (1, "pre")] },
    TypeInfo { id: 6, name: "boundary", fields: &[("value", K::I)], subtypes: &[(0, "cancel"), (1, "user"), (2, "protrusion"), (3, "word")] },
    TypeInfo { id: 7, name: "disc", fields: &[("pre", K::N), ("post", K::N), ("replace", K::N), ("penalty", K::I)], subtypes: &[(0, "discretionary"), (1, "explicit"), (2, "automatic"), (3, "regular"), (4, "first"), (5, "second")] },
    TypeInfo { id: 8, name: "whatsit", fields: &[], subtypes: &[] },
    TypeInfo { id: 9, name: "local_par", fields: &[("pen_inter", K::I), ("pen_broken", K::I), ("dir", K::D), ("box_left", K::N), ("box_left_width", K::I), ("box_right", K::N), ("box_right_width", K::I)], subtypes: &[] },
    TypeInfo { id: 10, name: "dir", fields: &[("dir", K::D), ("level", K::I)], subtypes: &[(0, "normal"), (1, "cancel")] },
    TypeInfo { id: 11, name: "math", fields: &[("surround", K::I), ("width", K::I), ("stretch", K::I), ("shrink", K::I), ("stretch_order", K::I), ("shrink_order", K::I)], subtypes: &[(0, "beginmath"), (1, "endmath")] },
    TypeInfo { id: 12, name: "glue", fields: &[("leader", K::N), ("width", K::I), ("stretch", K::I), ("shrink", K::I), ("stretch_order", K::I), ("shrink_order", K::I)], subtypes: &[(0, "userskip"), (1, "lineskip"), (2, "baselineskip"), (3, "parskip"), (4, "abovedisplayskip"), (5, "belowdisplayskip"), (6, "abovedisplayshortskip"), (7, "belowdisplayshortskip"), (8, "leftskip"), (9, "rightskip"), (10, "topskip"), (11, "splittopskip"), (12, "tabskip"), (13, "spaceskip"), (14, "xspaceskip"), (15, "parfillskip"), (16, "mathskip"), (17, "thinmuskip"), (18, "medmuskip"), (19, "thickmuskip"), (98, "conditionalmathskip"), (99, "muglue"), (100, "leaders"), (101, "cleaders"), (102, "xleaders"), (103, "gleaders")] },
    TypeInfo { id: 13, name: "kern", fields: &[("kern", K::I), ("expansion_factor", K::I)], subtypes: &[(0, "fontkern"), (1, "userkern"), (2, "accentkern"), (3, "italiccorrection")] },
    TypeInfo { id: 14, name: "penalty", fields: &[("penalty", K::I)], subtypes: &[(0, "userpenalty"), (1, "linebreakpenalty"), (2, "linepenalty"), (3, "wordpenalty"), (4, "finalpenalty"), (5, "noadpenalty"), (6, "beforedisplaypenalty"), (7, "afterdisplaypenalty"), (8, "equationnumberpenalty")] },
    TypeInfo { id: 15, name: "unset", fields: &[("width", K::I), ("depth", K::I), ("height", K::I), ("dir", K::D), ("shrink", K::I), ("glue_order", K::I), ("glue_sign", K::I), ("stretch", K::I), ("span", K::I), ("head", K::N)], subtypes: &[] },
    TypeInfo { id: 16, name: "style", fields: &[("style", K::I)], subtypes: &[] },
    TypeInfo { id: 17, name: "choice", fields: &[("display", K::N), ("text", K::N), ("script", K::N), ("scriptscript", K::N)], subtypes: &[] },
    TypeInfo { id: 18, name: "noad", fields: &[("nucleus", K::N), ("sub", K::N), ("sup", K::N)], subtypes: &[(0, "ord"), (1, "opdisplaylimits"), (2, "oplimits"), (3, "opnolimits"), (4, "bin"), (5, "rel"), (6, "open"), (7, "close"), (8, "punct"), (9, "inner"), (10, "under"), (11, "over"), (12, "vcenter")] },
    TypeInfo { id: 19, name: "radical", fields: &[("nucleus", K::N), ("sub", K::N), ("sup", K::N), ("left", K::N), ("degree", K::N), ("width", K::I), ("options", K::I)], subtypes: &[(0, "radical"), (1, "uradical"), (2, "uroot"), (3, "uunderdelimiter"), (4, "uoverdelimiter"), (5, "udelimiterunder"), (6, "udelimiterover")] },
    TypeInfo { id: 20, name: "fraction", fields: &[("width", K::I), ("num", K::N), ("denom", K::N), ("left", K::N), ("right", K::N), ("middle", K::N), ("fam", K::I), ("options", K::I)], subtypes: &[] },
    TypeInfo { id: 21, name: "accent", fields: &[("nucleus", K::N), ("sub", K::N), ("sup", K::N), ("accent", K::N), ("bot_accent", K::N), ("top_accent", K::N), ("overlay_accent", K::N), ("fraction", K::I)], subtypes: &[(0, "bothflexible"), (1, "fixedtop"), (2, "fixedbottom"), (3, "fixedboth")] },
    TypeInfo { id: 22, name: "fence", fields: &[("delim", K::N), ("italic", K::I), ("height", K::I), ("depth", K::I), ("options", K::I), ("class", K::I)], subtypes: &[(0, "unset"), (1, "left"), (2, "middle"), (3, "right"), (4, "no")] },
    TypeInfo { id: 23, name: "math_char", fields: &[("fam", K::I), ("char", K::I)], subtypes: &[] },
    TypeInfo { id: 24, name: "sub_box", fields: &[("head", K::N)], subtypes: &[] },
    TypeInfo { id: 25, name: "sub_mlist", fields: &[("head", K::N)], subtypes: &[] },
    TypeInfo { id: 26, name: "math_text_char", fields: &[("fam", K::I), ("char", K::I)], subtypes: &[] },
    TypeInfo { id: 27, name: "delim", fields: &[("small_fam", K::I), ("small_char", K::I), ("large_fam", K::I), ("large_char", K::I)], subtypes: &[] },
    TypeInfo { id: 28, name: "margin_kern", fields: &[("width", K::I), ("glyph", K::N)], subtypes: &[] },
    TypeInfo { id: 29, name: "glyph", fields: &[("char", K::I), ("font", K::I), ("lang", K::I), ("left", K::I), ("right", K::I), ("uchyph", K::I), ("components", K::N), ("xoffset", K::I), ("yoffset", K::I), ("width", K::I), ("height", K::I), ("depth", K::I), ("expansion_factor", K::I), ("data", K::I)], subtypes: &[(0, "unset"), (1, "character"), (2, "ligature"), (4, "ghost"), (8, "left"), (16, "right")] },
    TypeInfo { id: 30, name: "align_record", fields: &[], subtypes: &[] },
    TypeInfo { id: 31, name: "pseudo_file", fields: &[], subtypes: &[] },
    TypeInfo { id: 32, name: "pseudo_line", fields: &[], subtypes: &[] },
    TypeInfo { id: 33, name: "page_insert", fields: &[("height", K::I), ("last_ins_ptr", K::N), ("best_ins_ptr", K::N), ("width", K::I), ("stretch", K::I), ("shrink", K::I), ("stretch_order", K::I), ("shrink_order", K::I)], subtypes: &[] },
    TypeInfo { id: 34, name: "split_insert", fields: &[("height", K::I), ("last_ins_ptr", K::N), ("best_ins_ptr", K::N), ("broken_ptr", K::N), ("broken_ins", K::N)], subtypes: &[] },
    TypeInfo { id: 35, name: "expr_stack", fields: &[], subtypes: &[] },
    TypeInfo { id: 36, name: "nested_list", fields: &[], subtypes: &[] },
    TypeInfo { id: 37, name: "span", fields: &[], subtypes: &[] },
    TypeInfo { id: 38, name: "attribute", fields: &[("number", K::I), ("value", K::I)], subtypes: &[] },
    TypeInfo { id: 39, name: "glue_spec", fields: &[("width", K::I), ("stretch", K::I), ("shrink", K::I), ("stretch_order", K::I), ("shrink_order", K::I)], subtypes: &[] },
    TypeInfo { id: 40, name: "attribute_list", fields: &[], subtypes: &[] },
    TypeInfo { id: 41, name: "temp", fields: &[], subtypes: &[] },
    TypeInfo { id: 42, name: "align_stack", fields: &[], subtypes: &[] },
    TypeInfo { id: 43, name: "movement_stack", fields: &[], subtypes: &[] },
    TypeInfo { id: 44, name: "if_stack", fields: &[], subtypes: &[] },
    TypeInfo { id: 45, name: "unhyphenated", fields: &[], subtypes: &[] },
    TypeInfo { id: 46, name: "hyphenated", fields: &[], subtypes: &[] },
    TypeInfo { id: 47, name: "delta", fields: &[], subtypes: &[] },
    TypeInfo { id: 48, name: "passive", fields: &[], subtypes: &[] },
    TypeInfo { id: 49, name: "shape", fields: &[], subtypes: &[] },
];

pub struct WhatsitInfo { pub id: u8, pub name: &'static str, pub fields: &'static [(&'static str, K)] }

pub const WHATSITS: &[WhatsitInfo] = &[
    WhatsitInfo { id: 0, name: "open", fields: &[("stream", K::I), ("name", K::S), ("area", K::S), ("ext", K::S)] },
    WhatsitInfo { id: 1, name: "write", fields: &[("stream", K::I), ("data", K::S)] },
    WhatsitInfo { id: 2, name: "close", fields: &[("stream", K::I)] },
    WhatsitInfo { id: 3, name: "special", fields: &[("data", K::S)] },
    WhatsitInfo { id: 4, name: "late_special", fields: &[("data", K::S)] },
    WhatsitInfo { id: 7, name: "save_pos", fields: &[] },
    WhatsitInfo { id: 8, name: "late_lua", fields: &[("reg", K::I), ("data", K::S), ("name", K::S), ("string", K::S)] },
    WhatsitInfo { id: 9, name: "user_defined", fields: &[("user_id", K::I), ("type", K::I), ("value", K::V)] },
    WhatsitInfo { id: 16, name: "pdf_literal", fields: &[("mode", K::I), ("data", K::S)] },
    WhatsitInfo { id: 17, name: "pdf_late_literal", fields: &[("mode", K::I), ("data", K::S)] },
    WhatsitInfo { id: 18, name: "pdf_refobj", fields: &[("objnum", K::I)] },
    WhatsitInfo { id: 19, name: "pdf_annot", fields: &[("width", K::I), ("depth", K::I), ("height", K::I), ("objnum", K::I), ("data", K::S)] },
    WhatsitInfo { id: 20, name: "pdf_start_link", fields: &[("width", K::I), ("depth", K::I), ("height", K::I), ("objnum", K::I), ("link_attr", K::S), ("action", K::N)] },
    WhatsitInfo { id: 21, name: "pdf_end_link", fields: &[] },
    WhatsitInfo { id: 22, name: "pdf_dest", fields: &[("width", K::I), ("depth", K::I), ("height", K::I), ("named_id", K::I), ("dest_id", K::S), ("dest_type", K::I), ("xyz_zoom", K::I), ("objnum", K::I)] },
    WhatsitInfo { id: 23, name: "pdf_action", fields: &[("action_type", K::I), ("named_id", K::I), ("action_id", K::S), ("file", K::S), ("new_window", K::I), ("data", K::S), ("struct_id", K::S)] },
    WhatsitInfo { id: 24, name: "pdf_thread", fields: &[("width", K::I), ("depth", K::I), ("height", K::I), ("named_id", K::I), ("thread_id", K::S), ("thread_attr", K::S)] },
    WhatsitInfo { id: 25, name: "pdf_start_thread", fields: &[("width", K::I), ("depth", K::I), ("height", K::I), ("named_id", K::I), ("thread_id", K::S), ("thread_attr", K::S)] },
    WhatsitInfo { id: 26, name: "pdf_end_thread", fields: &[] },
    WhatsitInfo { id: 27, name: "pdf_thread_data", fields: &[] },
    WhatsitInfo { id: 28, name: "pdf_link_data", fields: &[] },
    WhatsitInfo { id: 29, name: "pdf_colorstack", fields: &[("stack", K::I), ("cmd", K::I), ("data", K::S)] },
    WhatsitInfo { id: 30, name: "pdf_setmatrix", fields: &[("data", K::S)] },
    WhatsitInfo { id: 31, name: "pdf_save", fields: &[] },
    WhatsitInfo { id: 32, name: "pdf_restore", fields: &[] },
    WhatsitInfo { id: 33, name: "pdf_link_state", fields: &[("value", K::I)] },
];

pub const HAS_ATTR: &[u8] = &[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29];

pub const HAS_SUBTYPE: &[u8] = &[0, 1, 2, 3, 4, 5, 6, 7, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 41, 42, 43, 44, 45, 46, 47, 48, 49];
