//! Primitive codes and named-parameter indices.
//!
//! Following tex.web's design: named parameters (`\tolerance`, `\hsize`, ...)
//! are primitives carrying a parameter index; the *values* live in per-kind
//! parameter tables with save-stack levels. Numbered registers
//! (`\count12`, `\skip3`, ...) are scanned as (register primitive, index)
//! pairs; `\countdef` etc. bind a control sequence to a register index.

#[derive(Clone, Copy, PartialEq, Eq, Debug)]
#[repr(u16)]
pub enum IntParam {
    Pretolerance = 0,
    Tolerance,
    LinePenalty,
    HyphenPenalty,
    ExHyphenPenalty,
    ClubPenalty,
    WidowPenalty,
    DisplayWidowPenalty,
    BrokenPenalty,
    BinOpPenalty,
    RelPenalty,
    PreDisplayPenalty,
    PostDisplayPenalty,
    InterLinePenalty,
    DoubleHyphenDemerits,
    FinalHyphenDemerits,
    AdjDemerits,
    Mag,
    DelimiterFactor,
    Looseness,
    Penalty,
    HBadness,
    VBadness,
    Pausing,
    TracingOnline,
    TracingMacros,
    TracingStats,
    TracingParagraphs,
    TracingPages,
    TracingOutput,
    TracingLostChars,
    TracingCommands,
    TracingRestores,
    TracingIf,
    TracingFonts,
    ShowBoxBreadth,
    ShowBoxDepth,
    ErrorStopMode,
    ScrollMode,
    NonStopMode,
    BatchMode,
    Language,
    UcHyph,
    LeftHyphenMin,
    RightHyphenMin,
    EscapeChar,
    EndLineChar,
    NewLineChar,
    Defaulthyphenchar,
    Defaultskewchar,
    ErrorContextLines,
    MaxDeadCycles,
    InsertPenalties,
    OutputPenalty,
    FloatingPenalty,
    HangAfter,
    PrevGraf,
    CurFam,
    Time,
    Day,
    Month,
    Year,
    InputLineNo,
    Badness,
    DeadCycles,
    EtxVersion,
    PdfOutput,
    PdfAdjustSpacing,
    PdfProtrudeChars,
    PdfMinorVersion,
    PdfPageCount,
    TeXXeTEnabled,
    PdfTexVersion,
    InteractionMode,
    CurrentGroupLevel,
    CurrentGroupType,
    CurrentIfLevel,
    CurrentIfType,
    CurrentIfBranch,
    LastNodeType,
    SavingHyphCodes,
    SavingVDiscards,
    PdfObjCompressLevel,
    PdfGenToUnicode,
    PaperQuality,
    GlobalDefs,
    /// e-TeX \tracingnesting (read/write int; we accept and store it,
    /// group tracing itself is not implemented)
    TracingNesting,
}

pub const NUM_INT_PARAMS: usize = 87;



impl IntParam {
    #[inline]
    pub fn idx(self) -> u16 {
        self as u16
    }
    pub fn from_idx(i: u16) -> Option<Self> {
        if (i as usize) < NUM_INT_PARAMS {
            Some(unsafe { std::mem::transmute::<u16, IntParam>(i) })
        } else {
            None
        }
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug)]
#[repr(u16)]
pub enum DimParam {
    ParIndent = 0,
    MathSurround,
    LineSkipLimit,
    HSize,
    VSize,
    MaxDepth,
    SplitMaxDepth,
    BoxMaxDepth,
    DisplayIndent,
    DisplayWidth,
    HangIndent,
    EmergencyStretch,
    PageGoal,
    PageTotal,
    PageDepth,
    PageStretch,
    PageFilStretch,
    PageFillStretch,
    PageFilllStretch,
    PageShrink,
    DelimiterShortfall,
    Hfuzz,
    Vfuzz,
    OverfullRule,
    NullDelimiterSpace,
    ScriptSpace,
    TopSkip,
    // pdfTeX page/origin driver dimensions (appended: stable indices 27+)
    PdfPageWidth,
    PdfPageHeight,
    PdfHOrigin,
    PdfVOrigin,
    PdfLinkMargin,
    PdfDestMargin,
    PdfThreadMargin,
    HOffset,
    VOffset,
    PrevDepth,
}

pub const NUM_DIM_PARAMS: usize = 37;

impl DimParam {
    #[inline]
    pub fn idx(self) -> u16 {
        self as u16
    }
    pub fn from_idx(i: u16) -> Option<Self> {
        if (i as usize) < NUM_DIM_PARAMS {
            Some(unsafe { std::mem::transmute::<u16, DimParam>(i) })
        } else {
            None
        }
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug)]
#[repr(u16)]
pub enum GlueParam {
    LineSkip = 0,
    BaselineSkip,
    ParSkip,
    LeftSkip,
    RightSkip,
    ParFillSkip,
    SpaceSkip,
    XSpaceSkip,
    AboveDisplaySkip,
    AboveDisplayShortSkip,
    BelowDisplaySkip,
    BelowDisplayShortSkip,
    SplitTopSkip,
    TabSkip,
    ThinMuSkip,
    MedMuSkip,
    ThickMuSkip,
}

pub const NUM_GLUE_PARAMS: usize = 17;

impl GlueParam {
    #[inline]
    pub fn idx(self) -> u16 {
        self as u16
    }
    #[inline]
    pub fn is_mu(self) -> bool {
        matches!(self, GlueParam::ThinMuSkip | GlueParam::MedMuSkip | GlueParam::ThickMuSkip)
    }
}



#[derive(Clone, Copy, PartialEq, Eq, Debug)]
#[repr(u16)]
pub enum ToksParam {
    EveryPar = 0,
    EveryMath,
    EveryDisplay,
    EveryHBox,
    EveryVBox,
    EveryJob,
    EveryCr,
    EveryEOF,
    Output,
    ErrHelp,
}

pub const NUM_TOKS_PARAMS: usize = 10;

impl ToksParam {
    #[inline]
    pub fn idx(self) -> u16 {
        self as u16
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Prim {
    // ---- expansion ----
    Relax,
    ExpandAfter,
    NoExpand,
    CsName,
    EndCsName,
    LastNamedCs,
    The,
    String,
    Meaning,
    Number,
    RomanNumeral,
    Lowercase,
    Uppercase,
    Detokenize,
    Expanded,
    UnExpanded,
    ScanTokens,
    NumExpr,
    DimExpr,
    GlueExpr,
    MuExpr,
    Input,
    EndInput,
    Dump,
    // ---- conditionals ----
    IfChar,
    IfCat,
    IfOdd,
    IfNum,
    IfDim,
    IfVoid,
    IfHBox,
    IfVBox,
    IfHMode,
    IfVMode,
    IfInner,
    IfMMode,
    IfTrue,
    IfFalse,
    IfEOF,
    IfDef,
    IfCSName,
    IfX,
    IfCase,
    IfFontChar,
    ElIf,
    ElIfX,
    Else,
    Or,
    Fi,
    Unless,
    // ---- grouping ----
    BGroup,
    EGroup,
    BeginGroup,
    EndGroup,
    // ---- definitions & prefixes ----
    Def,
    GDef,
    EDef,
    XDef,
    Let,
    FutureLet,
    Global,
    Long,
    Outer,
    Protected,
    // ---- registers & constants ----
    CatCode,
    MathCode,
    DelCode,
    LcCodeP,
    SfCodeP,
    UcCodeP,
    Count,
    Dimen,
    Skip,
    MuSkip,
    Toks,
    Box,
    CountDef,
    DimenDef,
    SkipDef,
    MuSkipDef,
    ToksDef,
    CharDef,
    MathCharDef,
    FontDimen,
    HyphenChar,
    SkewChar,
    ParShape,
    SetBox,
    Advance,
    Multiply,
    Divide,
    // ---- named parameters ----
    IntP(IntParam),
    DimP(DimParam),
    GlueP(GlueParam),
    ToksP(ToksParam),
    // ---- fonts ----
    Font,
    FontName,
    FontIdPrim,
    // ---- horizontal/vertical material ----
    HSkip,
    VSkip,
    MSkip,
    HFil,
    HFill,
    HFilL,
    HFilNeg,
    HSS,
    VFil,
    VFill,
    VFilL,
    VFilNeg,
    VSS,
    Kern,
    MKern,
    HMove,
    VMove,
    HBox,
    VBox,
    VTop,
    VCenter,
    HRule,
    VRule,
    Leaders,
    CLeaders,
    XLeaders,
    Wd,
    Ht,
    Dp,
    Par,
    Indent,
    NoIndent,
    UnSkip,
    UnKern,
    UnPenalty,
    LastBox,
    LastKern,
    LastPenalty,
    LastSkip,
    VSplit,
    Penalties,
    Penalty,
    Insert,
    VAdjust,
    MarkPrim,
    TopMark,
    FirstMark,
    BotMark,
    SplitFirstMark,
    SplitBotMark,
    ShipOut,
    // ---- math ----
    MathChar,
    MathAccent,
    Radical,
    Delimiter,
    Above,
    Over,
    Atop,
    OverWithDelims,
    AtopWithDelims,
    AboveWithDelims,
    TextFont,
    ScriptFont,
    ScriptScriptFont,
    Left,
    Right,
    Middle,
    NoLimits,
    Limits,
    DisplayLimits,
    MathChoice,
    // ---- alignment ----
    Span,
    Cr,
    CrCr,
    Omit,
    NoAlign,
    HAlign,
    VAlign,
    // ---- io ----
    Immediate,
    OpenOut,
    CloseOut,
    Write,
    Special,
    Message,
    ErrMessage,
    OpenIn,
    CloseIn,
    Read,
    ReadLine,
    JobName,
    // ---- introspection ----
    Show,
    ShowBox,
    ShowThe,
    ShowLists,
    ShowGroups,
    ShowTokens,
    ShowIfs,
    // ---- pdfTeX ----
    PdfLiteral,
    PdfSave,
    PdfRestore,
    PdfSetMatrix,
    PdfStartLink,
    PdfEndLink,
    PdfDest,
    PdfOutline,
    PdfInfo,
    PdfCatalog,
    PdfAnnot,
    PdfColorStackInit,
    PdfColorStack,
    PdfColorStackPrim,
    PdfSavePos,
    PdfLastXPos,
    PdfLastYPos,
    PdfTexRevision,
    UcharCat,
    PdfMapFile,
    PdfMapLine,
    PdfGlyphToUnicode,
    PdfFontAttr,
    PdfXForm,
    PdfXImage,
    PdfRefXForm,
    PdfRefXImage,
    PdfPagesAttr,
    PdfCompressorLevel,
    PdfObj,
    PdfRefObj,
    PdfUncompress,
    PdfTolerance,
    PdfHOrigin,
    PdfVOrigin,
    PdfPageWidth,
    PdfPageHeight,
    PdfPageBox,
    PdfThread,
    PdfStartThread,
    PdfEndThread,
    PdfLinkMargin,
    PdfDestMargin,
    PdfThreadMargin,
    PdfFileSize,
    PdfMdFiveSum,
    PdfFileModDate,
    PdfFileDump,
    PdfStrCmp,
    PdfShellEscape,
    PdfElapsedTime,
    PdfResetTimer,
    PdfUniformDeviate,
    PdfNormalDeviate,
    PdfEscapeString,
    PdfEscapeName,
    PdfEscapeHex,
    PdfUnescapeHex,
    FileSize,
    // ---- misc ----
    // ---- appended: pdfTeX hyperref/navigation primitives (stable codes
    //      249+, keep new unit variants at the tail so earlier codes hold)
    PdfNames,
    PdfPageAttr,
    End,
    IfInCsName,
    UnHBox,
    UnVBox,
    UnHCopy,
    UnVCopy,
    AfterAssignment,
    AfterGroup,
    // ---- appended: pdfTeX read-only object counters (stable codes 258+,
    //      keep new unit variants at the tail so earlier codes hold)
    PdfLastObj,
    PdfLastXForm,
    PdfLastXImage,
    PdfLastLink,
    PdfLastAnnot,
    IgnoreSpaces,
    /// LuaTeX no-op stub: swallow `{...}` so a false-positive Lua path in
    /// `everyjob` does not typeset the Lua source.
    DirectLua,
    GlueStretch,
    GlueShrink,
    GlueStretchOrder,
    GlueShrinkOrder,
    /// Knuth \\copy: insert/set a box without voiding the register.
    Copy,
    Overline,
    Underline,
    Char,
    MathOrd,
    MathOp,
    MathBin,
    MathRel,
    MathOpen,
    MathClose,
    MathPunct,
    MathInner,
    DisplayStyle,
    TextStyle,
    ScriptStyle,
    ScriptScriptStyle,
 }



/// Stable wire codes for the format dump (`crate::format`). Unit variants
/// take 0..0x0fff in declaration order — exhaustiveness is compiler-checked
/// in `code`; new unit variants MUST be appended at the enum tail so earlier
/// codes keep their values. The four parameter families occupy dedicated
/// high ranges that carry the parameter index directly.
impl Prim {
    pub fn code(self) -> u16 {
        match self {
            Prim::Relax => 0,
            Prim::ExpandAfter => 1,
            Prim::NoExpand => 2,
            Prim::CsName => 3,
            Prim::EndCsName => 4,
            Prim::LastNamedCs => 5,
            Prim::The => 6,
            Prim::String => 7,
            Prim::Meaning => 8,
            Prim::Number => 9,
            Prim::RomanNumeral => 10,
            Prim::Lowercase => 11,
            Prim::Uppercase => 12,
            Prim::Detokenize => 13,
            Prim::Expanded => 14,
            Prim::UnExpanded => 15,
            Prim::ScanTokens => 16,
            Prim::NumExpr => 17,
            Prim::DimExpr => 18,
            Prim::GlueExpr => 19,
            Prim::MuExpr => 20,
            Prim::Input => 21,
            Prim::EndInput => 22,
            Prim::Dump => 23,
            Prim::IfChar => 24,
            Prim::IfCat => 25,
            Prim::IfOdd => 26,
            Prim::IfNum => 27,
            Prim::IfDim => 28,
            Prim::IfVoid => 29,
            Prim::IfHBox => 30,
            Prim::IfVBox => 31,
            Prim::IfHMode => 32,
            Prim::IfVMode => 33,
            Prim::IfInner => 34,
            Prim::IfMMode => 35,
            Prim::IfTrue => 36,
            Prim::IfFalse => 37,
            Prim::IfEOF => 38,
            Prim::IfDef => 39,
            Prim::IfCSName => 40,
            Prim::IfX => 41,
            Prim::IfCase => 42,
            Prim::IfFontChar => 285,
            Prim::ElIf => 43,
            Prim::ElIfX => 44,
            Prim::Else => 45,
            Prim::Or => 46,
            Prim::Fi => 47,
            Prim::Unless => 48,
            Prim::BGroup => 49,
            Prim::EGroup => 50,
            Prim::BeginGroup => 51,
            Prim::EndGroup => 52,
            Prim::Def => 53,
            Prim::GDef => 54,
            Prim::EDef => 55,
            Prim::XDef => 56,
            Prim::Let => 57,
            Prim::FutureLet => 58,
            Prim::Global => 59,
            Prim::Long => 60,
            Prim::Outer => 61,
            Prim::Protected => 62,
            Prim::CatCode => 63,
            Prim::MathCode => 64,
            Prim::DelCode => 65,
            Prim::LcCodeP => 66,
            Prim::SfCodeP => 67,
            Prim::UcCodeP => 68,
            Prim::Count => 69,
            Prim::Dimen => 70,
            Prim::Skip => 71,
            Prim::MuSkip => 72,
            Prim::Toks => 73,
            Prim::Box => 74,
            Prim::CountDef => 75,
            Prim::DimenDef => 76,
            Prim::SkipDef => 77,
            Prim::MuSkipDef => 78,
            Prim::ToksDef => 79,
            Prim::CharDef => 80,
            Prim::MathCharDef => 81,
            Prim::FontDimen => 82,
            Prim::HyphenChar => 83,
            Prim::SkewChar => 84,
            Prim::ParShape => 286,
            Prim::SetBox => 85,
            Prim::Advance => 86,
            Prim::Multiply => 87,
            Prim::Divide => 88,
            Prim::Font => 89,
            Prim::FontName => 90,
            Prim::FontIdPrim => 91,
            Prim::HSkip => 92,
            Prim::VSkip => 93,
            Prim::MSkip => 94,
            Prim::HFil => 95,
            Prim::HFill => 96,
            Prim::HFilL => 97,
            Prim::HFilNeg => 98,
            Prim::HSS => 99,
            Prim::VFil => 100,
            Prim::VFill => 101,
            Prim::VFilL => 102,
            Prim::VFilNeg => 103,
            Prim::VSS => 104,
            Prim::Kern => 105,
            Prim::MKern => 106,
            Prim::HMove => 107,
            Prim::VMove => 108,
            Prim::HBox => 109,
            Prim::VBox => 110,
            Prim::VTop => 111,
            Prim::VCenter => 112,
            Prim::HRule => 113,
            Prim::VRule => 114,
            Prim::Leaders => 115,
            Prim::CLeaders => 116,
            Prim::XLeaders => 117,
            Prim::Wd => 118,
            Prim::Ht => 119,
            Prim::Dp => 120,
            Prim::Par => 121,
            Prim::Indent => 122,
            Prim::NoIndent => 123,
            Prim::UnSkip => 124,
            Prim::UnKern => 125,
            Prim::UnPenalty => 126,
            Prim::LastBox => 127,
            Prim::LastKern => 128,
            Prim::LastPenalty => 129,
            Prim::LastSkip => 130,
            Prim::VSplit => 131,
            Prim::Penalties => 132,
            Prim::Penalty => 133,
            Prim::Insert => 134,
            Prim::VAdjust => 135,
            Prim::MarkPrim => 136,
            Prim::TopMark => 137,
            Prim::FirstMark => 138,
            Prim::BotMark => 139,
            Prim::SplitFirstMark => 140,
            Prim::SplitBotMark => 141,
            Prim::ShipOut => 142,
            Prim::MathChar => 143,
            Prim::MathAccent => 144,
            Prim::Radical => 145,
            Prim::Delimiter => 146,
            Prim::Above => 147,
            Prim::Over => 148,
            Prim::Atop => 149,
            Prim::OverWithDelims => 150,
            Prim::AtopWithDelims => 151,
            Prim::AboveWithDelims => 152,
            Prim::TextFont => 153,
            Prim::ScriptFont => 154,
            Prim::ScriptScriptFont => 155,
            Prim::Left => 156,
            Prim::Right => 157,
            Prim::Middle => 158,
            Prim::NoLimits => 159,
            Prim::Limits => 160,
            Prim::DisplayLimits => 161,
            Prim::MathChoice => 162,
            Prim::Span => 163,
            Prim::Cr => 164,
            Prim::CrCr => 165,
            Prim::Omit => 166,
            Prim::NoAlign => 167,
            Prim::HAlign => 168,
            Prim::VAlign => 169,
            Prim::Immediate => 170,
            Prim::OpenOut => 171,
            Prim::CloseOut => 172,
            Prim::Write => 173,
            Prim::Special => 174,
            Prim::Message => 175,
            Prim::ErrMessage => 176,
            Prim::OpenIn => 177,
            Prim::CloseIn => 178,
            Prim::Read => 179,
            Prim::ReadLine => 180,
            Prim::JobName => 181,
            Prim::Show => 182,
            Prim::ShowBox => 183,
            Prim::ShowThe => 184,
            Prim::ShowLists => 185,
            Prim::ShowGroups => 186,
            Prim::ShowTokens => 187,
            Prim::ShowIfs => 188,
            Prim::PdfLiteral => 189,
            Prim::PdfSave => 190,
            Prim::PdfRestore => 191,
            Prim::PdfSetMatrix => 192,
            Prim::PdfStartLink => 193,
            Prim::PdfEndLink => 194,
            Prim::PdfDest => 195,
            Prim::PdfOutline => 196,
            Prim::PdfInfo => 197,
            Prim::PdfCatalog => 198,
            Prim::PdfAnnot => 199,
            Prim::PdfColorStackInit => 200,
            Prim::PdfColorStack => 201,
            Prim::PdfColorStackPrim => 202,
            Prim::PdfSavePos => 203,
            Prim::PdfLastXPos => 204,
            Prim::PdfLastYPos => 205,
            Prim::PdfTexRevision => 206,
            Prim::UcharCat => 207,
            Prim::PdfMapFile => 208,
            Prim::PdfMapLine => 209,
            Prim::PdfGlyphToUnicode => 210,
            Prim::PdfFontAttr => 211,
            Prim::PdfXForm => 212,
            Prim::PdfXImage => 213,
            Prim::PdfRefXForm => 214,
            Prim::PdfRefXImage => 215,
            Prim::PdfPagesAttr => 216,
            Prim::PdfCompressorLevel => 217,
            Prim::PdfObj => 218,
            Prim::PdfRefObj => 219,
            Prim::PdfUncompress => 220,
            Prim::PdfTolerance => 221,
            Prim::PdfHOrigin => 222,
            Prim::PdfVOrigin => 223,
            Prim::PdfPageWidth => 224,
            Prim::PdfPageHeight => 225,
            Prim::PdfPageBox => 226,
            Prim::PdfThread => 227,
            Prim::PdfStartThread => 228,
            Prim::PdfEndThread => 229,
            Prim::PdfLinkMargin => 230,
            Prim::PdfDestMargin => 231,
            Prim::PdfThreadMargin => 232,
            Prim::PdfFileSize => 233,
            Prim::PdfMdFiveSum => 234,
            Prim::PdfFileModDate => 235,
            Prim::PdfFileDump => 236,
            Prim::PdfStrCmp => 237,
            Prim::PdfShellEscape => 238,
            Prim::PdfElapsedTime => 239,
            Prim::PdfResetTimer => 240,
            Prim::PdfUniformDeviate => 241,
            Prim::PdfNormalDeviate => 242,
            Prim::PdfEscapeString => 243,
            Prim::PdfEscapeName => 244,
            Prim::PdfEscapeHex => 245,
            Prim::PdfUnescapeHex => 246,
            Prim::FileSize => 247,
            Prim::PdfNames => 248,
            Prim::PdfPageAttr => 249,
            Prim::End => 250,
            Prim::IfInCsName => 251,
            Prim::UnHBox => 252,
            Prim::UnVBox => 253,
            Prim::UnHCopy => 254,
            Prim::UnVCopy => 255,
            Prim::AfterAssignment => 256,
            Prim::AfterGroup => 257,
            Prim::PdfLastObj => 258,
            Prim::PdfLastXForm => 259,
            Prim::PdfLastXImage => 260,
            Prim::PdfLastLink => 261,
            Prim::PdfLastAnnot => 262,
            Prim::IgnoreSpaces => 263,
            Prim::DirectLua => 264,
            Prim::GlueStretch => 265,
            Prim::GlueShrink => 266,
            Prim::GlueStretchOrder => 267,
            Prim::GlueShrinkOrder => 268,
            Prim::Copy => 269,
            Prim::Overline => 270,
            Prim::Underline => 271,
            Prim::Char => 272,
            Prim::MathOrd => 273,
            Prim::MathOp => 274,
            Prim::MathBin => 275,
            Prim::MathRel => 276,
            Prim::MathOpen => 277,
            Prim::MathClose => 278,
            Prim::MathPunct => 279,
            Prim::MathInner => 280,
            Prim::DisplayStyle => 281,
            Prim::TextStyle => 282,
            Prim::ScriptStyle => 283,
            Prim::ScriptScriptStyle => 284,
            Prim::IntP(p) => 0x1000 | p.idx(),
            Prim::DimP(p) => 0x2000 | p.idx(),
            Prim::GlueP(p) => 0x3000 | p.idx(),
            Prim::ToksP(p) => 0x4000 | p.idx(),
        }
    }

    pub fn from_code(c: u16) -> Option<Prim> {
        match c {
            0 => Some(Prim::Relax),
            1 => Some(Prim::ExpandAfter),
            2 => Some(Prim::NoExpand),
            3 => Some(Prim::CsName),
            4 => Some(Prim::EndCsName),
            5 => Some(Prim::LastNamedCs),
            6 => Some(Prim::The),
            7 => Some(Prim::String),
            8 => Some(Prim::Meaning),
            9 => Some(Prim::Number),
            10 => Some(Prim::RomanNumeral),
            11 => Some(Prim::Lowercase),
            12 => Some(Prim::Uppercase),
            13 => Some(Prim::Detokenize),
            14 => Some(Prim::Expanded),
            15 => Some(Prim::UnExpanded),
            16 => Some(Prim::ScanTokens),
            17 => Some(Prim::NumExpr),
            18 => Some(Prim::DimExpr),
            19 => Some(Prim::GlueExpr),
            20 => Some(Prim::MuExpr),
            21 => Some(Prim::Input),
            22 => Some(Prim::EndInput),
            23 => Some(Prim::Dump),
            24 => Some(Prim::IfChar),
            25 => Some(Prim::IfCat),
            26 => Some(Prim::IfOdd),
            27 => Some(Prim::IfNum),
            28 => Some(Prim::IfDim),
            29 => Some(Prim::IfVoid),
            30 => Some(Prim::IfHBox),
            31 => Some(Prim::IfVBox),
            32 => Some(Prim::IfHMode),
            33 => Some(Prim::IfVMode),
            34 => Some(Prim::IfInner),
            35 => Some(Prim::IfMMode),
            36 => Some(Prim::IfTrue),
            37 => Some(Prim::IfFalse),
            38 => Some(Prim::IfEOF),
            39 => Some(Prim::IfDef),
            40 => Some(Prim::IfCSName),
            41 => Some(Prim::IfX),
            42 => Some(Prim::IfCase),
            43 => Some(Prim::ElIf),
            44 => Some(Prim::ElIfX),
            45 => Some(Prim::Else),
            46 => Some(Prim::Or),
            47 => Some(Prim::Fi),
            48 => Some(Prim::Unless),
            49 => Some(Prim::BGroup),
            50 => Some(Prim::EGroup),
            51 => Some(Prim::BeginGroup),
            52 => Some(Prim::EndGroup),
            53 => Some(Prim::Def),
            54 => Some(Prim::GDef),
            55 => Some(Prim::EDef),
            56 => Some(Prim::XDef),
            57 => Some(Prim::Let),
            58 => Some(Prim::FutureLet),
            59 => Some(Prim::Global),
            60 => Some(Prim::Long),
            61 => Some(Prim::Outer),
            62 => Some(Prim::Protected),
            63 => Some(Prim::CatCode),
            64 => Some(Prim::MathCode),
            65 => Some(Prim::DelCode),
            66 => Some(Prim::LcCodeP),
            67 => Some(Prim::SfCodeP),
            68 => Some(Prim::UcCodeP),
            69 => Some(Prim::Count),
            70 => Some(Prim::Dimen),
            71 => Some(Prim::Skip),
            72 => Some(Prim::MuSkip),
            73 => Some(Prim::Toks),
            74 => Some(Prim::Box),
            75 => Some(Prim::CountDef),
            76 => Some(Prim::DimenDef),
            77 => Some(Prim::SkipDef),
            78 => Some(Prim::MuSkipDef),
            79 => Some(Prim::ToksDef),
            80 => Some(Prim::CharDef),
            81 => Some(Prim::MathCharDef),
            82 => Some(Prim::FontDimen),
            83 => Some(Prim::HyphenChar),
            84 => Some(Prim::SkewChar),
            285 => Some(Prim::IfFontChar),
            286 => Some(Prim::ParShape),
            85 => Some(Prim::SetBox),
            86 => Some(Prim::Advance),
            87 => Some(Prim::Multiply),
            88 => Some(Prim::Divide),
            89 => Some(Prim::Font),
            90 => Some(Prim::FontName),
            91 => Some(Prim::FontIdPrim),
            92 => Some(Prim::HSkip),
            93 => Some(Prim::VSkip),
            94 => Some(Prim::MSkip),
            95 => Some(Prim::HFil),
            96 => Some(Prim::HFill),
            97 => Some(Prim::HFilL),
            98 => Some(Prim::HFilNeg),
            99 => Some(Prim::HSS),
            100 => Some(Prim::VFil),
            101 => Some(Prim::VFill),
            102 => Some(Prim::VFilL),
            103 => Some(Prim::VFilNeg),
            104 => Some(Prim::VSS),
            105 => Some(Prim::Kern),
            106 => Some(Prim::MKern),
            107 => Some(Prim::HMove),
            108 => Some(Prim::VMove),
            109 => Some(Prim::HBox),
            110 => Some(Prim::VBox),
            111 => Some(Prim::VTop),
            112 => Some(Prim::VCenter),
            113 => Some(Prim::HRule),
            114 => Some(Prim::VRule),
            115 => Some(Prim::Leaders),
            116 => Some(Prim::CLeaders),
            117 => Some(Prim::XLeaders),
            118 => Some(Prim::Wd),
            119 => Some(Prim::Ht),
            120 => Some(Prim::Dp),
            121 => Some(Prim::Par),
            122 => Some(Prim::Indent),
            123 => Some(Prim::NoIndent),
            124 => Some(Prim::UnSkip),
            125 => Some(Prim::UnKern),
            126 => Some(Prim::UnPenalty),
            127 => Some(Prim::LastBox),
            128 => Some(Prim::LastKern),
            129 => Some(Prim::LastPenalty),
            130 => Some(Prim::LastSkip),
            131 => Some(Prim::VSplit),
            132 => Some(Prim::Penalties),
            133 => Some(Prim::Penalty),
            134 => Some(Prim::Insert),
            135 => Some(Prim::VAdjust),
            136 => Some(Prim::MarkPrim),
            137 => Some(Prim::TopMark),
            138 => Some(Prim::FirstMark),
            139 => Some(Prim::BotMark),
            140 => Some(Prim::SplitFirstMark),
            141 => Some(Prim::SplitBotMark),
            142 => Some(Prim::ShipOut),
            143 => Some(Prim::MathChar),
            144 => Some(Prim::MathAccent),
            145 => Some(Prim::Radical),
            146 => Some(Prim::Delimiter),
            147 => Some(Prim::Above),
            148 => Some(Prim::Over),
            149 => Some(Prim::Atop),
            150 => Some(Prim::OverWithDelims),
            151 => Some(Prim::AtopWithDelims),
            152 => Some(Prim::AboveWithDelims),
            153 => Some(Prim::TextFont),
            154 => Some(Prim::ScriptFont),
            155 => Some(Prim::ScriptScriptFont),
            156 => Some(Prim::Left),
            157 => Some(Prim::Right),
            158 => Some(Prim::Middle),
            159 => Some(Prim::NoLimits),
            160 => Some(Prim::Limits),
            161 => Some(Prim::DisplayLimits),
            162 => Some(Prim::MathChoice),
            163 => Some(Prim::Span),
            164 => Some(Prim::Cr),
            165 => Some(Prim::CrCr),
            166 => Some(Prim::Omit),
            167 => Some(Prim::NoAlign),
            168 => Some(Prim::HAlign),
            169 => Some(Prim::VAlign),
            170 => Some(Prim::Immediate),
            171 => Some(Prim::OpenOut),
            172 => Some(Prim::CloseOut),
            173 => Some(Prim::Write),
            174 => Some(Prim::Special),
            175 => Some(Prim::Message),
            176 => Some(Prim::ErrMessage),
            177 => Some(Prim::OpenIn),
            178 => Some(Prim::CloseIn),
            179 => Some(Prim::Read),
            180 => Some(Prim::ReadLine),
            181 => Some(Prim::JobName),
            182 => Some(Prim::Show),
            183 => Some(Prim::ShowBox),
            184 => Some(Prim::ShowThe),
            185 => Some(Prim::ShowLists),
            186 => Some(Prim::ShowGroups),
            187 => Some(Prim::ShowTokens),
            188 => Some(Prim::ShowIfs),
            189 => Some(Prim::PdfLiteral),
            190 => Some(Prim::PdfSave),
            191 => Some(Prim::PdfRestore),
            192 => Some(Prim::PdfSetMatrix),
            193 => Some(Prim::PdfStartLink),
            194 => Some(Prim::PdfEndLink),
            195 => Some(Prim::PdfDest),
            196 => Some(Prim::PdfOutline),
            197 => Some(Prim::PdfInfo),
            198 => Some(Prim::PdfCatalog),
            199 => Some(Prim::PdfAnnot),
            200 => Some(Prim::PdfColorStackInit),
            201 => Some(Prim::PdfColorStack),
            202 => Some(Prim::PdfColorStackPrim),
            203 => Some(Prim::PdfSavePos),
            204 => Some(Prim::PdfLastXPos),
            205 => Some(Prim::PdfLastYPos),
            206 => Some(Prim::PdfTexRevision),
            207 => Some(Prim::UcharCat),
            208 => Some(Prim::PdfMapFile),
            209 => Some(Prim::PdfMapLine),
            210 => Some(Prim::PdfGlyphToUnicode),
            211 => Some(Prim::PdfFontAttr),
            212 => Some(Prim::PdfXForm),
            213 => Some(Prim::PdfXImage),
            214 => Some(Prim::PdfRefXForm),
            215 => Some(Prim::PdfRefXImage),
            216 => Some(Prim::PdfPagesAttr),
            217 => Some(Prim::PdfCompressorLevel),
            218 => Some(Prim::PdfObj),
            219 => Some(Prim::PdfRefObj),
            220 => Some(Prim::PdfUncompress),
            221 => Some(Prim::PdfTolerance),
            222 => Some(Prim::PdfHOrigin),
            223 => Some(Prim::PdfVOrigin),
            224 => Some(Prim::PdfPageWidth),
            225 => Some(Prim::PdfPageHeight),
            226 => Some(Prim::PdfPageBox),
            227 => Some(Prim::PdfThread),
            228 => Some(Prim::PdfStartThread),
            229 => Some(Prim::PdfEndThread),
            230 => Some(Prim::PdfLinkMargin),
            231 => Some(Prim::PdfDestMargin),
            232 => Some(Prim::PdfThreadMargin),
            233 => Some(Prim::PdfFileSize),
            234 => Some(Prim::PdfMdFiveSum),
            235 => Some(Prim::PdfFileModDate),
            236 => Some(Prim::PdfFileDump),
            237 => Some(Prim::PdfStrCmp),
            238 => Some(Prim::PdfShellEscape),
            239 => Some(Prim::PdfElapsedTime),
            240 => Some(Prim::PdfResetTimer),
            241 => Some(Prim::PdfUniformDeviate),
            242 => Some(Prim::PdfNormalDeviate),
            243 => Some(Prim::PdfEscapeString),
            244 => Some(Prim::PdfEscapeName),
            245 => Some(Prim::PdfEscapeHex),
            246 => Some(Prim::PdfUnescapeHex),
            247 => Some(Prim::FileSize),
            248 => Some(Prim::PdfNames),
            249 => Some(Prim::PdfPageAttr),
            250 => Some(Prim::End),
            251 => Some(Prim::IfInCsName),
            252 => Some(Prim::UnHBox),
            253 => Some(Prim::UnVBox),
            254 => Some(Prim::UnHCopy),
            255 => Some(Prim::UnVCopy),
            256 => Some(Prim::AfterAssignment),
            257 => Some(Prim::AfterGroup),
            258 => Some(Prim::PdfLastObj),
            259 => Some(Prim::PdfLastXForm),
            260 => Some(Prim::PdfLastXImage),
            261 => Some(Prim::PdfLastLink),
            262 => Some(Prim::PdfLastAnnot),
            263 => Some(Prim::IgnoreSpaces),
            264 => Some(Prim::DirectLua),
            265 => Some(Prim::GlueStretch),
            266 => Some(Prim::GlueShrink),
            267 => Some(Prim::GlueStretchOrder),
            268 => Some(Prim::GlueShrinkOrder),
            269 => Some(Prim::Copy),
            270 => Some(Prim::Overline),
            271 => Some(Prim::Underline),
            272 => Some(Prim::Char),
            273 => Some(Prim::MathOrd),
            274 => Some(Prim::MathOp),
            275 => Some(Prim::MathBin),
            276 => Some(Prim::MathRel),
            277 => Some(Prim::MathOpen),
            278 => Some(Prim::MathClose),
            279 => Some(Prim::MathPunct),
            280 => Some(Prim::MathInner),
            281 => Some(Prim::DisplayStyle),
            282 => Some(Prim::TextStyle),
            283 => Some(Prim::ScriptStyle),
            284 => Some(Prim::ScriptScriptStyle),

            0x1000..=0x1fff => {
                let i = c & 0x0fff;
                Some(Prim::IntP(IntParam::from_idx(i)?))
            }
            0x2000..=0x2fff => {
                let i = c & 0x0fff;
                Some(Prim::DimP(DimParam::from_idx(i)?))
            }
            0x3000..=0x3fff => {
                let i = c & 0x0fff;
                if (i as usize) >= NUM_GLUE_PARAMS { return None; }
                Some(Prim::GlueP(match i { 0 => GlueParam::LineSkip, 1 => GlueParam::BaselineSkip, 2 => GlueParam::ParSkip, 3 => GlueParam::LeftSkip, 4 => GlueParam::RightSkip, 5 => GlueParam::ParFillSkip, 6 => GlueParam::SpaceSkip, 7 => GlueParam::XSpaceSkip, 8 => GlueParam::AboveDisplaySkip, 9 => GlueParam::AboveDisplayShortSkip, 10 => GlueParam::BelowDisplaySkip, 11 => GlueParam::BelowDisplayShortSkip, 12 => GlueParam::SplitTopSkip, 13 => GlueParam::TabSkip, 14 => GlueParam::ThinMuSkip, 15 => GlueParam::MedMuSkip, 16 => GlueParam::ThickMuSkip, _ => return None }))
            }
            0x4000..=0x4fff => {
                let i = c & 0x0fff;
                if (i as usize) >= NUM_TOKS_PARAMS { return None; }
                Some(Prim::ToksP(match i { 0 => ToksParam::EveryPar, 1 => ToksParam::EveryMath, 2 => ToksParam::EveryDisplay, 3 => ToksParam::EveryHBox, 4 => ToksParam::EveryVBox, 5 => ToksParam::EveryJob, 6 => ToksParam::EveryCr, 7 => ToksParam::EveryEOF, 8 => ToksParam::Output, 9 => ToksParam::ErrHelp, _ => return None }))
            }
            _ => None,
        }
    }
}
