//! Primitive codes and named-parameter indices.
//!
//! Following tex.web's design: named parameters (`\tolerance`, `\hsize`, ...)
//! are primitives carrying a parameter index; the *values* live in per-kind
//! parameter tables with save-stack levels. Numbered registers
//! (`\count12`, `\skip3`, ...) are scanned as (register primitive, index)
//! pairs; `\countdef` etc. bind a control sequence to a register index.

#[derive(Clone, Copy, PartialEq, Eq, Debug)]
#[repr(u16)]
pub enum IntParam {
    Pretolerance = 0,
    Tolerance,
    LinePenalty,
    HyphenPenalty,
    ExHyphenPenalty,
    ClubPenalty,
    WidowPenalty,
    DisplayWidowPenalty,
    BrokenPenalty,
    BinOpPenalty,
    RelPenalty,
    PreDisplayPenalty,
    PostDisplayPenalty,
    InterLinePenalty,
    DoubleHyphenDemerits,
    FinalHyphenDemerits,
    AdjDemerits,
    Mag,
    DelimiterFactor,
    Looseness,
    Penalty,
    HBadness,
    VBadness,
    Pausing,
    TracingOnline,
    TracingMacros,
    TracingStats,
    TracingParagraphs,
    TracingPages,
    TracingOutput,
    TracingLostChars,
    TracingCommands,
    TracingRestores,
    TracingIf,
    TracingFonts,
    ShowBoxBreadth,
    ShowBoxDepth,
    ErrorStopMode,
    ScrollMode,
    NonStopMode,
    BatchMode,
    Language,
    UcHyph,
    LeftHyphenMin,
    RightHyphenMin,
    EscapeChar,
    EndLineChar,
    NewLineChar,
    Defaulthyphenchar,
    Defaultskewchar,
    ErrorContextLines,
    MaxDeadCycles,
    InsertPenalties,
    OutputPenalty,
    FloatingPenalty,
    HangAfter,
    PrevGraf,
    CurFam,
    Time,
    Day,
    Month,
    Year,
    InputLineNo,
    Badness,
    DeadCycles,
    EtxVersion,
    PdfOutput,
    PdfAdjustSpacing,
    PdfProtrudeChars,
    PdfMinorVersion,
    PdfPageCount,
    TeXXeTEnabled,
    PdfTexVersion,
}

pub const NUM_INT_PARAMS: usize = 73;

impl IntParam {
    #[inline]
    pub fn idx(self) -> u16 {
        self as u16
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug)]
#[repr(u16)]
pub enum DimParam {
    ParIndent = 0,
    MathSurround,
    LineSkipLimit,
    HSize,
    VSize,
    MaxDepth,
    SplitMaxDepth,
    BoxMaxDepth,
    DisplayIndent,
    DisplayWidth,
    HangIndent,
    EmergencyStretch,
    PageGoal,
    PageTotal,
    PageDepth,
    PageStretch,
    PageFilStretch,
    PageFillStretch,
    PageFilllStretch,
    PageShrink,
    DelimiterShortfall,
    Hfuzz,
    Vfuzz,
    OverfullRule,
    NullDelimiterSpace,
    ScriptSpace,
    TopSkip,
}

pub const NUM_DIM_PARAMS: usize = 27;

impl DimParam {
    #[inline]
    pub fn idx(self) -> u16 {
        self as u16
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug)]
#[repr(u16)]
pub enum GlueParam {
    LineSkip = 0,
    BaselineSkip,
    ParSkip,
    LeftSkip,
    RightSkip,
    ParFillSkip,
    SpaceSkip,
    XSpaceSkip,
    AboveDisplaySkip,
    AboveDisplayShortSkip,
    BelowDisplaySkip,
    BelowDisplayShortSkip,
    SplitTopSkip,
    TabSkip,
}

pub const NUM_GLUE_PARAMS: usize = 14;

impl GlueParam {
    #[inline]
    pub fn idx(self) -> u16 {
        self as u16
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug)]
#[repr(u16)]
pub enum ToksParam {
    EveryPar = 0,
    EveryMath,
    EveryDisplay,
    EveryHBox,
    EveryVBox,
    EveryJob,
    EveryCr,
    EveryEOF,
    Output,
}

pub const NUM_TOKS_PARAMS: usize = 9;

impl ToksParam {
    #[inline]
    pub fn idx(self) -> u16 {
        self as u16
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Prim {
    // ---- expansion ----
    Relax,
    ExpandAfter,
    NoExpand,
    CsName,
    EndCsName,
    LastNamedCs,
    The,
    String,
    Meaning,
    Number,
    RomanNumeral,
    Lowercase,
    Uppercase,
    Detokenize,
    Expanded,
    UnExpanded,
    ScanTokens,
    NumExpr,
    DimExpr,
    GlueExpr,
    MuExpr,
    Input,
    EndInput,
    Dump,
    // ---- conditionals ----
    IfChar,
    IfCat,
    IfOdd,
    IfNum,
    IfDim,
    IfVoid,
    IfHBox,
    IfVBox,
    IfHMode,
    IfVMode,
    IfInner,
    IfMMode,
    IfTrue,
    IfFalse,
    IfEOF,
    IfDef,
    IfCSName,
    IfX,
    IfCase,
    ElIf,
    ElIfX,
    Else,
    Or,
    Fi,
    Unless,
    // ---- grouping ----
    BGroup,
    EGroup,
    BeginGroup,
    EndGroup,
    // ---- definitions & prefixes ----
    Def,
    GDef,
    EDef,
    XDef,
    Let,
    FutureLet,
    Global,
    Long,
    Outer,
    Protected,
    // ---- registers & constants ----
    CatCode,
    MathCode,
    DelCode,
    LcCodeP,
    SfCodeP,
    UcCodeP,
    Count,
    Dimen,
    Skip,
    MuSkip,
    Toks,
    Box,
    CountDef,
    DimenDef,
    SkipDef,
    MuSkipDef,
    ToksDef,
    CharDef,
    MathCharDef,
    FontDimen,
    HyphenChar,
    SkewChar,
    SetBox,
    Advance,
    Multiply,
    Divide,
    // ---- named parameters ----
    IntP(IntParam),
    DimP(DimParam),
    GlueP(GlueParam),
    ToksP(ToksParam),
    // ---- fonts ----
    Font,
    FontName,
    FontIdPrim,
    // ---- horizontal/vertical material ----
    HSkip,
    VSkip,
    MSkip,
    HFil,
    HFill,
    HFilL,
    HFilNeg,
    HSS,
    VFil,
    VFill,
    VFilL,
    VFilNeg,
    VSS,
    Kern,
    MKern,
    HMove,
    VMove,
    HBox,
    VBox,
    VTop,
    VCenter,
    HRule,
    VRule,
    Leaders,
    CLeaders,
    XLeaders,
    Wd,
    Ht,
    Dp,
    Par,
    Indent,
    NoIndent,
    UnSkip,
    UnKern,
    UnPenalty,
    LastBox,
    LastKern,
    LastPenalty,
    LastSkip,
    VSplit,
    Penalties,
    Penalty,
    Insert,
    VAdjust,
    MarkPrim,
    TopMark,
    FirstMark,
    BotMark,
    SplitFirstMark,
    SplitBotMark,
    ShipOut,
    // ---- math ----
    MathChar,
    MathAccent,
    Radical,
    Delimiter,
    Above,
    Over,
    Atop,
    OverWithDelims,
    AtopWithDelims,
    AboveWithDelims,
    TextFont,
    ScriptFont,
    ScriptScriptFont,
    Left,
    Right,
    Middle,
    NoLimits,
    Limits,
    DisplayLimits,
    MathChoice,
    // ---- alignment ----
    Span,
    Cr,
    CrCr,
    Omit,
    NoAlign,
    HAlign,
    VAlign,
    // ---- io ----
    Immediate,
    OpenOut,
    CloseOut,
    Write,
    Special,
    Message,
    ErrMessage,
    OpenIn,
    CloseIn,
    Read,
    ReadLine,
    JobName,
    // ---- introspection ----
    Show,
    ShowBox,
    ShowThe,
    ShowLists,
    ShowGroups,
    ShowTokens,
    ShowIfs,
    // ---- pdfTeX ----
    PdfLiteral,
    PdfSave,
    PdfRestore,
    PdfSetMatrix,
    PdfStartLink,
    PdfEndLink,
    PdfDest,
    PdfOutline,
    PdfInfo,
    PdfCatalog,
    PdfAnnot,
    PdfColorStackInit,
    PdfColorStack,
    PdfColorStackPrim,
    PdfSavePos,
    PdfLastXPos,
    PdfLastYPos,
    PdfTexRevision,
    UcharCat,
    PdfMapFile,
    PdfMapLine,
    PdfGlyphToUnicode,
    PdfFontAttr,
    PdfXForm,
    PdfXImage,
    PdfRefXForm,
    PdfRefXImage,
    PdfPagesAttr,
    PdfCompressorLevel,
    PdfObj,
    PdfRefObj,
    PdfUncompress,
    PdfTolerance,
    PdfHOrigin,
    PdfVOrigin,
    PdfPageWidth,
    PdfPageHeight,
    PdfPageBox,
    PdfThread,
    PdfStartThread,
    PdfEndThread,
    PdfLinkMargin,
    PdfDestMargin,
    PdfThreadMargin,
    PdfFileSize,
    PdfMdFiveSum,
    PdfFileModDate,
    PdfFileDump,
    PdfStrCmp,
    PdfShellEscape,
    PdfElapsedTime,
    PdfResetTimer,
    PdfUniformDeviate,
    PdfNormalDeviate,
    PdfEscapeString,
    PdfEscapeName,
    PdfEscapeHex,
    PdfUnescapeHex,
    FileSize,
    // ---- misc ----
    End,
}
