[package]
name = "tex-core"
version.workspace = true
edition.workspace = true

[dependencies]
tex-kpse = { path = "../tex-kpse" }
tex-lua = { path = "../tex-lua" }
tex-mplib = { path = "../tex-mplib" }
tex-ps = { path = "../tex-ps" }
flate2 = { workspace = true }
crc32fast = "1.5"
ruzstd = { workspace = true }
rustybuzz = { workspace = true }
ttf-parser = { workspace = true }
subsetter = "0.2.6"
unicode-linebreak = "0.1"
unicode-segmentation = "1.12"
smallvec = "1.16"
lopdf = { version = "0.44.0", default-features = false }
png = "0.18.1"
posix-regex = "0.1.4"
md5 = "0.8"
libc = { workspace = true }
