//! Datasource decoding compatible with Perl Encode (Biber 2.22).
//! Mapping data is generated by scripts/generate-biber-encoding.pl.
use std::collections::BTreeMap;
use std::sync::LazyLock;
use regex::Regex;
include!("encoding_tables.rs");
const DATA: &[u8] = include_bytes!("encoding_tables.bin");

pub fn decode(bytes: &[u8], encoding: &str) -> Result<String, String> {
    let mut text = decode_raw(bytes, encoding)?;
    if text.starts_with('\u{feff}') { drop(text.drain(..'\u{feff}'.len_utf8())); }
    if !text.chars().any(|c| matches!(c, '\r' | '\u{b}' | '\u{c}' | '\u{85}' | '\u{2028}' | '\u{2029}')) { return Ok(text); }
    let mut out = String::with_capacity(text.len());
    let mut chars = text.chars().peekable();
    while let Some(c) = chars.next() {
        if c == '\r' { if chars.peek() == Some(&'\n') { chars.next(); } out.push('\n'); }
        else if matches!(c, '\n' | '\u{b}' | '\u{c}' | '\u{85}' | '\u{2028}' | '\u{2029}') { out.push('\n'); }
        else { out.push(c); }
    }
    Ok(out)
}
fn decode_raw(bytes: &[u8], encoding: &str) -> Result<String, String> {
    let name = resolve(encoding).ok_or_else(|| format!("Unknown encoding '{encoding}'"))?;
    match name.as_str() {
        "utf8" | "utf-8-strict" => {
            let text=std::str::from_utf8(bytes).map_err(|e| format!("{encoding} does not map to Unicode at byte {}", e.valid_up_to()))?;
            if name=="utf-8-strict" {if let Some((i,_))=text.char_indices().find(|(_,c)|noncharacter(*c as u32)){return Err(format!("{encoding} does not map to Unicode at byte {i}"));}}
            Ok(text.to_owned())
        }
        "utf-16" | "utf-16be" | "utf-16le" | "ucs-2be" | "ucs-2le" | "utf-32" | "utf-32be" | "utf-32le" => unicode(bytes, &name),
        "utf-7" => utf7(bytes),
        "hz" | "7bit-jis" | "iso-2022-jp" | "iso-2022-jp-1" | "iso-2022-kr" => stateful(bytes, &name),
        n if n.starts_with("mime-") => mime(bytes, n),
        _ => table_decode(bytes, &name),
    }
}

/// Biber reads control files as UTF-8, with a Latin-1 fallback, before XML parsing.
/// UTF-16/32 control files consequently remain malformed, as in the oracle.
pub fn decode_bcf(bytes: &[u8]) -> Result<String, String> {
    decode_raw(bytes, "UTF-8").or_else(|_| decode_raw(bytes, "iso-8859-1"))
}

/// Encode::find_encoding as Biber configures it: canonical names first, then
/// Encode::Alias::find_alias over Biber's and Encode's aliases, newest first.
fn resolve(label: &str) -> Option<String> {
    // File::Slurper uses Perl's ||= default, including the string "0".
    if label.is_empty() || label == "0" { return Some("utf-8-strict".to_owned()); }
    get_encoding(label, &mut BTreeMap::new())
}
/// Encoding names Encode registers with mixed case (Encode::Config, Encode::Unicode, MIME).
const MIXED_CASE: &[&str] = &["AdobeStandardEncoding","AdobeSymbol","AdobeZdingbat","MacArabic","MacCentralEurRoman","MacChineseSimp","MacChineseTrad","MacCroatian","MacCyrillic","MacDingbats","MacFarsi","MacGreek","MacHebrew","MacIcelandic","MacJapanese","MacKorean","MacRoman","MacRomanian","MacRumanian","MacSami","MacSymbol","MacThai","MacTurkish","MacUkrainian","UCS-2BE","UCS-2LE","UTF-16","UTF-16BE","UTF-16LE","UTF-32","UTF-32BE","UTF-32LE","UTF-7","MIME-Header","MIME-B","MIME-Q","MIME-Header-ISO_2022_JP"];
/// Exact `%Encoding`/`%ExtModule` key lookup, returning this module's lowercase name.
fn canonical(name: &str) -> Option<String> {
    if MIXED_CASE.contains(&name) { return Some(name.to_ascii_lowercase()); }
    let lower = name.to_ascii_lowercase();
    if lower != name || MIXED_CASE.iter().any(|m| m.eq_ignore_ascii_case(name)) { return None; }
    (TABLES.iter().any(|(n,_,_)| *n == name) || matches!(name, "utf8" | "utf-8-strict" | "7bit-jis" | "iso-2022-jp" | "iso-2022-jp-1" | "iso-2022-kr" | "hz")).then(|| name.to_owned())
}
/// Encode::getEncoding (whitespace removed; exact, lowercase, alias, alias of lowercase).
fn get_encoding(name: &str, seen: &mut BTreeMap<String, Option<String>>) -> Option<String> {
    let name: String = name.chars().filter(|c| !crate::perl_unicode::is_space(*c)).collect();
    let lower = name.to_lowercase();
    canonical(&name).or_else(|| canonical(&lower))
        .or_else(|| find_alias(&name, seen))
        .or_else(|| if lower != name { find_alias(&lower, seen) } else { None })
}
enum Alias { Pattern(Regex, fn(&regex::Captures) -> Option<String>), Fixed(Regex, &'static str), Name(&'static str, &'static str), Gb2312 }
/// `@Encode::Alias::Alias` after init_aliases and Biber::Constants, in lookup order.
static ALIAS_LIST: LazyLock<Vec<Alias>> = LazyLock::new(|| {
    fn re(pattern: &str, f: fn(&regex::Captures) -> Option<String>) -> Alias { Alias::Pattern(Regex::new(pattern).unwrap(), f) }
    fn fixed(pattern: &str, target: &'static str) -> Alias { Alias::Fixed(Regex::new(pattern).unwrap(), target) }
    vec![
        Alias::Name("lutf8","UTF-8"), Alias::Name("x-ascii","ascii"), Alias::Name("x-nextstep","MacRoman"), Alias::Name("x-mac-cyrillic","MacCyrillic"),
        Alias::Name("x-mac-centeuro","MacCentralEurRoman"), Alias::Name("x-mac-roman","MacRoman"), Alias::Name("next","MacRoman"),
        Alias::Name("applemacce","MacCentralEurRoman"), Alias::Name("applemac","MacRoman"), Alias::Name("ansinew","cp1252"),
        re(r"(?i)^([^\s_]+)[\s_]+([^\s_]*)$", |c| Some(format!("{}-{}", &c[1], &c[2]))),
        fixed(r"(?i)\bUTF-8$", "utf-8-strict"), fixed(r"(?i)cp65001", "utf-8-strict"), fixed(r"(?i)cp65000", "UTF-7"),
        fixed(r"(?i)\bhk(?:scs)?[-_]?big5$", "big5-hkscs"), fixed(r"(?i)\bbig5-?hk(?:scs)?$", "big5-hkscs"),
        fixed(r"(?i)\btca[-_]?big5$", "big5-eten"), fixed(r"(?i)\bbig5-?et(?:en)?$", "big5-eten"), fixed(r"(?i)\bbig-?5$", "big5-eten"),
        fixed(r"(?i)\bks_c_5601-1987$", "cp949"), fixed(r"(?i)(?:x-)?windows-949$", "cp949"), fixed(r"(?i)(?:x-)?uhc$", "cp949"),
        fixed(r"(?i)\bkr.*euc$", "euc-kr"), fixed(r"(?i)\beuc.*kr$", "euc-kr"),
        fixed(r"(?i)\bwindows-31j$", "cp932"), fixed(r"(?i)\bsjis$", "shiftjis"), fixed(r"(?i)\bshift.*jis$", "shiftjis"),
        fixed(r"(?i)\bujis$", "euc-jp"), fixed(r"(?i)\bjp.*euc$", "euc-jp"), fixed(r"(?i)\beuc.*jp$", "euc-jp"), fixed(r"(?i)\bjis$", "7bit-jis"),
        Alias::Gb2312, fixed(r"(?i)^gbk$", "cp936"), fixed(r"(?i)\bcn.*euc$", "euc-cn"), fixed(r"(?i)\beuc.*cn$", "euc-cn"),
        re(r"(?i)\bkoi8[\s\-_]*([ru])$", |c| Some(format!("koi8-{}", &c[1]))),
        fixed(r"(?i)^macce$", "MacCentralEurRoman"), fixed(r"(?i)^macintosh$", "MacRoman"),
        re(r"(?i)^(?:x[_-])?mac[_-](.*)$", |c| Some(format!("mac{}", &c[1]))),
        re(r"(?i)\b(?:cp|ibm|ms|windows)[-_ ]?(\d{2,4})$", |c| Some(format!("cp{}", &c[1]))),
        fixed(r"(?i)\btis-?620\b", "iso-8859-11"),
        Alias::Name("thai","iso-8859-11"), Alias::Name("hebrew","iso-8859-8"), Alias::Name("greek","iso-8859-7"),
        Alias::Name("arabic","iso-8859-6"), Alias::Name("cyrillic","iso-8859-5"), Alias::Name("ascii","US-ascii"),
        re(r"(?i)\bwin(latin[12]|cyrillic|baltic|greek|turkish|hebrew|arabic|baltic|vietnamese)$", |c| {
            let cp = match c[1].to_lowercase().as_str() {"latin1"=>1252,"latin2"=>1250,"cyrillic"=>1251,"greek"=>1253,"turkish"=>1254,"hebrew"=>1255,"arabic"=>1256,"baltic"=>1257,_=>1258};
            Some(format!("cp{cp}"))
        }),
        re(r"(?i)\b(?:iso[-_]?)?latin[-_]?(\d+)$", |c| {
            // $Latin2iso[$1]: Perl numifies the digits; out-of-range indices are undef.
            const LATIN2ISO: [u32; 11] = [0, 1, 2, 3, 4, 9, 10, 13, 14, 15, 16];
            let index = c[1].trim_start_matches('0');
            let index = if index.is_empty() { Some(0) } else { index.parse::<usize>().ok() };
            index.and_then(|i| LATIN2ISO.get(i)).map(|n| format!("iso-8859-{n}"))
        }),
        re(r"(?i)^(.+)@euro$", |c| Some(c[1].to_owned())),
        fixed(r"(?i)\bANSI[-_]?X3\.4[-_]?1968$", "ascii"),
        re(r"(?i)\b(?:hp-)?(arabic|greek|hebrew|kana|roman|thai|turkish)8$", |c| Some(format!("{}8", &c[1]))),
        re(r"(?i)\biso8859(\d+)$", |c| Some(format!("iso-8859-{}", &c[1]))),
        fixed(r"(?i)\biso[-_]8859[-_]8[-_]I$", "iso-8859-8"),
        re(r"(?i)\biso[-_]?(\d+)[-_](\d+)$", |c| Some(format!("iso-{}-{}", &c[1], &c[2]))),
        fixed(r"(?i)\b(?:ISO[-_]?)?646(?:[-_]?US)?$", "ascii"),
        Alias::Name("C","ascii"),
        fixed(r"(?i)^(?:US-?)ascii$", "ascii"),
        re(r"(?i)^UTF-?(16|32)$", |c| Some(format!("UTF-{}", &c[1]))),
        re(r"(?i)^UTF-?(16|32)-?LE$", |c| Some(format!("UTF-{}LE", &c[1]))),
        re(r"(?i)^UTF-?(16|32)-?BE$", |c| Some(format!("UTF-{}BE", &c[1]))),
        fixed(r"(?i)^iso-10646-1$", "UCS-2BE"),
        re(r"(?i)^UCS-?4-?(BE|LE|)?$", |c| Some(format!("UTF-32{}", c.get(1).map_or("", |m| m.as_str())).to_uppercase())),
        fixed(r"(?i)^UCS-?2-?(BE)?$", "UCS-2BE"),
        fixed(r"(?i)^UCS-?2-?LE$", "UCS-2LE"),
        fixed(r"(?i)^(unicode-1-1-)?UTF-?7$", "UTF-7"),
        re(r"^(.*)$", |c| Some(c[1].to_lowercase())),
    ]
});
/// Encode::Alias::find_alias: the first alias whose result is itself an encoding wins;
/// a name under resolution resolves to nothing (Perl's recursion guard).
fn find_alias(find: &str, seen: &mut BTreeMap<String, Option<String>>) -> Option<String> {
    if let Some(found) = seen.get(find) { return found.clone(); }
    seen.insert(find.to_owned(), None);
    let mut result = None;
    for alias in ALIAS_LIST.iter() {
        let new = match alias {
            Alias::Pattern(re, f) => re.captures(find).and_then(|c| f(&c)),
            Alias::Fixed(re, target) => re.is_match(find).then(|| (*target).to_owned()),
            Alias::Name(name, target) => name.eq_ignore_ascii_case(find).then(|| (*target).to_owned()),
            // qr/\bGB[-_ ]?2312(?!-?raw)/i
            Alias::Gb2312 => {
                static GB: LazyLock<Regex> = LazyLock::new(|| Regex::new(r"(?i)\bGB[-_ ]?2312").unwrap());
                static RAW: LazyLock<Regex> = LazyLock::new(|| Regex::new(r"(?i)^-?raw").unwrap());
                GB.find_iter(find).any(|m| !RAW.is_match(&find[m.end()..])).then(|| "euc-cn".to_owned())
            }
        };
        let Some(new) = new else { continue };
        if new == find { continue; }
        if let Some(found) = get_encoding(&new, seen) { result = Some(found); break; }
    }
    // RT #7835: case-insensitive match against registered encoding names.
    if result.is_none() {
        let lower = find.to_lowercase();
        result = MIXED_CASE.iter().find(|m| m.to_lowercase() == lower).map(|m| m.to_ascii_lowercase()).or_else(|| canonical(&lower));
    }
    seen.insert(find.to_owned(), result.clone());
    result
}
fn word(bytes: &[u8], i:usize) -> u32 { u32::from_le_bytes(bytes[i..i+4].try_into().unwrap()) }
fn mapped(name:&str, key:u32, out:&mut String)->bool {
    let Some((_,offset,count))=TABLES.iter().find(|(n,_,_)| *n==name) else {return false};
    mapped_table(*offset, *count, key, out)
}
fn mapped_table(offset: usize, count: usize, key: u32, out: &mut String) -> bool {
    let (mut lo,mut hi)=(0,count);
    while lo<hi { let mid=(lo+hi)/2; let k=word(DATA,offset+mid*36); if k<key {lo=mid+1;} else {hi=mid;} }
    if lo==count || word(DATA,offset+lo*36)!=key {return false;}
    for i in 1..9 { let cp=word(DATA,offset+lo*36+i*4); if cp==u32::MAX {break;} out.push(char::from_u32(cp).unwrap()); }
    true
}
fn table_decode(bytes:&[u8],name:&str)->Result<String,String> {
    let (_, offset, count) = TABLES.iter().find(|(n,_,_)| *n == name).ok_or_else(|| format!("Unknown encoding '{name}'"))?;
    let mut out=String::with_capacity(bytes.len()); let mut i=0;
    while i<bytes.len() {
        let mut found=false;
        for len in 1..=3 { if i+len>bytes.len(){break;} let key=bytes[i..i+len].iter().fold((len as u32)<<24,|k,b| (k&0xff000000)|((k&0xffffff)<<8)|u32::from(*b));
            if mapped_table(*offset,*count,key,&mut out){i+=len;found=true;break;}
        }
        if !found { return Err(format!("{name} \"\\x{:02X}\" does not map to Unicode at byte {i}",bytes[i])); }
    }
    Ok(out)
}
fn unicode(mut bytes:&[u8],name:&str)->Result<String,String> {
    let width=if name.starts_with("utf-32"){4}else{2}; let mut le=name.ends_with("le");
    if name=="utf-16" { if bytes.starts_with(&[0xff,0xfe]){le=true;bytes=&bytes[2..];}else if bytes.starts_with(&[0xfe,0xff]){bytes=&bytes[2..];} }
    if name=="utf-32" { if bytes.starts_with(&[0xff,0xfe,0,0]){le=true;bytes=&bytes[4..];}else if bytes.starts_with(&[0,0,0xfe,0xff]){bytes=&bytes[4..];} }
    if bytes.len()%width!=0{return Err(format!("{name}:Partial character"));}
    let mut out=String::with_capacity(bytes.len()); let mut i=0;
    while i<bytes.len() { let mut cp=if width==4 {let a=bytes[i..i+4].try_into().unwrap();if le{u32::from_le_bytes(a)}else{u32::from_be_bytes(a)}}else{let a=bytes[i..i+2].try_into().unwrap();u32::from(if le{u16::from_le_bytes(a)}else{u16::from_be_bytes(a)})}; i+=width;
        if width==2 && (0xd800..=0xdbff).contains(&cp) && !name.starts_with("ucs") {if i==bytes.len(){return Err(format!("{name}:Malformed HI surrogate {cp:x}"));} let a=bytes[i..i+2].try_into().unwrap();let low=u32::from(if le{u16::from_le_bytes(a)}else{u16::from_be_bytes(a)}); if !(0xdc00..=0xdfff).contains(&low){return Err(format!("{name}:Malformed HI surrogate {cp:x}"));}i+=2;cp=0x10000+((cp-0xd800)<<10)+(low-0xdc00);}
        if noncharacter(cp) {return Err(format!("{name}:Unicode character {cp:x} is illegal"));}
        out.push(char::from_u32(cp).ok_or_else(||format!("{name}:Invalid Unicode character {cp:x}"))?);
    }
    Ok(out)
}
fn utf7(bytes:&[u8])->Result<String,String> {
    let mut out=String::new();let mut i=0;
    while i<bytes.len(){if bytes[i]!=b'+'{out.push(char::from(bytes[i]));i+=1;continue;}i+=1;if bytes.get(i)==Some(&b'-'){out.push('+');i+=1;continue;}
        let start=i;let mut bits=0u32;let mut n=0;let mut units=Vec::new();
        while let Some(b)=bytes.get(i){let v=match b {b'A'..=b'Z'=>b-b'A',b'a'..=b'z'=>b-b'a'+26,b'0'..=b'9'=>b-b'0'+52,b'+'=>62,b'/'=>63,_=>break};bits=(bits<<6)|u32::from(v);n+=6;i+=1;if n>=16{n-=16;units.push((bits>>n)as u16);bits&=(1<<n)-1;}}
        if i==start {out.push('+');continue;}
        for c in char::decode_utf16(units){let c=c.unwrap_or('\u{fffd}');out.push(if matches!(c,'\u{fffe}'|'\u{ffff}') {'\u{fffd}'} else {c});}if bytes.get(i)==Some(&b'-'){i+=1;}
    }Ok(out)
}
fn stateful(bytes:&[u8],name:&str)->Result<String,String> {
    if name == "hz" {
        let mut out=String::new(); let mut ascii=true; let mut i=0;
        while i<bytes.len() {
            if ascii {
                match (bytes[i],bytes.get(i+1)) {
                    (b'~',Some(b'{'))=>{ascii=false;i+=2;},
                    (b'~',Some(b'~'))=>{out.push('~');i+=2;},
                    (b'~',Some(b'\n'))=>{i+=2;},
                    (b'~',_)=>break,
                    (b,_) if b<0x80=>{out.push(char::from(b));i+=1;},
                    _=>break,
                }
            } else if bytes[i..].starts_with(b"~}") {ascii=true;i+=2;}
            else if i+1<bytes.len() && (0x21..=0x77).contains(&bytes[i]) && (0x21..=0x7e).contains(&bytes[i+1]) {
                let key=0x2000000|u32::from(bytes[i])<<8|u32::from(bytes[i+1]);
                if !mapped("gb2312-raw",key,&mut out) {return Err(format!("gb2312-raw does not map to Unicode at byte {i}"));}
                i+=2;
            } else {break;}
        }
        return Ok(out);
    }
    let mut converted=Vec::with_capacity(bytes.len()); let mut i=0;
    if name=="iso-2022-kr" {
        while i<bytes.len() {
            if bytes[i..].starts_with(b"\x1b$)C") {i+=4;continue;}
            converted.push(bytes[i]);i+=1;
        }
        // The Perl wrapper removes every designator before shifting complete SO/SI spans.
        let mut read=0;let mut written=0;
        while read<converted.len(){
            if converted[read]==0x0e {
                if let Some(end)=converted[read+1..].iter().position(|b|*b==0x0f){
                    let end=read+1+end;read+=1;
                    while read<end {let b=converted[read];converted[written]=if (0x21..=0x7e).contains(&b){b+0x80}else{b};written+=1;read+=1;}
                    read+=1;continue;
                }
            }
            converted[written]=converted[read];written+=1;read+=1;
        }
        converted.truncate(written);
        if let Some(escape)=converted.iter().position(|b|*b==0x1b){converted.truncate(escape);}
        return perlqq(&converted,"euc-kr");
    }
    let mut set=0;
    while i<bytes.len() && bytes[i]<0x80 {
        if bytes[i]==0x1b {
            let choices:&[(&[u8],u8)]=&[(b"\x1b(B",0),(b"\x1b(J",0),(b"\x1b(I",1),(b"\x1b$@",2),(b"\x1b$B",2),(b"\x1b$(D",3),(b"\x1b&@\x1b$B",2)];
            if let Some((seq,next))=choices.iter().find(|(seq,_)|bytes[i..].starts_with(seq)) {set=*next;i+=seq.len();continue;}
            break;
        }
        let b=bytes[i];
        if set==0 || !(0x21..=0x7e).contains(&b) {converted.push(b);i+=1;continue;}
        if set==1 && b<=0x5f {converted.extend([0x8e,b+0x80]);i+=1;continue;}
        if set==3 && i+1<bytes.len() && (0x21..=0x7e).contains(&bytes[i+1]) {
            converted.extend([0x8f,b+0x80,bytes[i+1]+0x80]);i+=2;continue;
        }
        converted.push(b+0x80);i+=1;
    }
    perlqq(&converted,"euc-jp")
}
// Stateful Perl wrappers explicitly request FB_PERLQQ, even under FB_CROAK.
fn perlqq(bytes:&[u8], name:&str)->Result<String,String> {
    use std::fmt::Write;
    let (_,offset,count)=TABLES.iter().find(|(n,_,_)| *n==name).unwrap();
    let mut out=String::new();let mut i=0;
    while i<bytes.len() {
        let width=if name=="euc-jp"&&bytes[i]==0x8f{3}else if (0xa1..=0xfe).contains(&bytes[i])||(name=="euc-jp"&&bytes[i]==0x8e){2}else{1};
        if bytes.len()-i<width{break;}
        let mut found=false;
        for len in 1..=3 {if i+len>bytes.len(){break;}let key=((len as u32)<<24)|bytes[i..i+len].iter().fold(0u32,|k,b|(k<<8)|u32::from(*b));if mapped_table(*offset,*count,key,&mut out){i+=len;found=true;break;}}
        if !found {write!(&mut out,"\\x{:02X}",bytes[i]).unwrap();i+=1;}
    }
    Ok(out)
}
fn mime(bytes: &[u8], name: &str) -> Result<String, String> {
    static WORD: LazyLock<Regex> = LazyLock::new(|| Regex::new(r"=\?([^?]+)\?([bBqQ])\?([^?]*)\?=").unwrap());
    let input: String = bytes.iter().map(|b| char::from(*b)).collect();
    let mut out = String::new();
    let mut end = 0;
    for c in WORD.captures_iter(&input) {
        let span = c.get(0).unwrap();
        let between = &input[end..span.start()];
        if end == 0 || !between.chars().all(char::is_whitespace) { out.push_str(between); }
        let base64 = c[2].eq_ignore_ascii_case("b");
        if (name == "mime-b" && !base64) || (name == "mime-q" && base64) {
            return Err(format!("MIME \"{}\" unsupported", &c[2]));
        }
        let mut decoded = Vec::new();
        if base64 {
            let mut bits = 0u32; let mut n = 0;
            for b in c[3].bytes() {
                let v = match b { b'A'..=b'Z'=>b-b'A', b'a'..=b'z'=>b-b'a'+26, b'0'..=b'9'=>b-b'0'+52, b'+'=>62, b'/'=>63, _=>continue };
                bits=(bits<<6)|u32::from(v); n+=6;
                if n>=8 { n-=8; decoded.push((bits>>n) as u8); bits &= (1<<n)-1; }
            }
        } else {
            let value: Vec<u8> = c[3].chars().map(|c| c as u8).collect(); let mut i=0;
            while i<value.len() {
                if value[i]==b'=' && i+2<value.len() {
                    if let (Some(hi), Some(lo)) = (char::from(value[i+1]).to_digit(16), char::from(value[i+2]).to_digit(16)) { decoded.push((hi*16+lo) as u8); i+=3; continue; }
                }
                decoded.push(if value[i]==b'_' {b' '} else {value[i]}); i+=1;
            }
        }
        out.push_str(&decode(&decoded, &c[1])?);
        end=span.end();
    }
    out.push_str(&input[end..]);
    Ok(out)
}

const OUTPUT_DATA: &[u8] = include_bytes!("encoding_output_tables.bin");

/// Encode's default substitution is used to detect entries requiring TeX recoding.
pub fn encode(text: &str, encoding: &str) -> Result<Vec<u8>, String> {
    encode_with_fallback(text, encoding, Fallback::Default)
}

/// File::Slurper's final output uses FB_PERLQQ rather than silently losing characters.
pub fn encode_output(text: &str, encoding: &str) -> Result<Vec<u8>, String> {
    encode_with_fallback(text, encoding, Fallback::Quoted)
}

/// BBL recoding detection uses Encode's callback substitution, not a literal question mark.
pub fn encode_probe(text: &str, encoding: &str) -> Result<Vec<u8>, String> {
    encode_with_fallback(text, encoding, Fallback::Nul)
}

#[derive(Clone, Copy, PartialEq)]
enum Fallback { Default, Quoted, Nul }

fn encode_with_fallback(text: &str, encoding: &str, fallback: Fallback) -> Result<Vec<u8>, String> {
    let name = resolve(encoding).ok_or_else(|| format!("Unknown encoding '{encoding}'"))?;
    if name == "utf8" || (name == "utf-8-strict" && !text.chars().any(|c| noncharacter(c as u32))) { return Ok(text.as_bytes().to_vec()); }
    if name == "utf-8-strict" {
        let mut out = Vec::with_capacity(text.len());
        for c in text.chars() { let mut bytes = [0; 16]; out.extend(utf8_scalar(c, fallback, &mut bytes)); }
        return Ok(out);
    }
    if name.starts_with("mime-") { return encode_mime(text, &name, fallback); }
    if name.starts_with("utf-16") || name.starts_with("utf-32") || name.starts_with("ucs-2") {
        let mut out = Vec::with_capacity(text.len() * 2 + 4);
        let le = name.ends_with("le");
        if name == "utf-16" { out.extend([0xfe, 0xff]); }
        if name == "utf-32" { out.extend([0, 0, 0xfe, 0xff]); }
        for c in text.chars() {
            let c = if noncharacter(c as u32) { '\u{fffd}' } else { c };
            if name.starts_with("utf-32") {
                out.extend(if le { (c as u32).to_le_bytes() } else { (c as u32).to_be_bytes() });
            } else {
                let mut units = [0; 2];
                let c = if name.starts_with("ucs-2") && c as u32 > 0xffff { '\u{fffd}' } else { c };
                for &unit in c.encode_utf16(&mut units).iter() {
                    out.extend(if le { unit.to_le_bytes() } else { unit.to_be_bytes() });
                }
            }
        }
        return Ok(out);
    }
    if name == "utf-7" { return Ok(encode_utf7(text)); }
    let (_, offset, count) = ENCODE_TABLES.iter().find(|(n, _, _)| *n == name).ok_or_else(|| format!("Unknown encoding '{encoding}'"))?;
    let substitution = ENCODE_SUBSTITUTIONS.iter().find(|(n, _)| *n == name).unwrap().1;
    let mut out = Vec::with_capacity(text.len());
    let mut output_state = 0;
    if name == "iso-2022-kr" { out.extend(b"\x1b$)C"); }
    let mut input = text;
    while let Some(c) = input.chars().next() {
        let cp = c as u32;
        let (mut lo, mut hi) = (0, *count);
        while lo < hi {
            let mid = (lo + hi) / 2;
            if word(OUTPUT_DATA, offset + mid * 68) < cp { lo = mid + 1; } else { hi = mid; }
        }
        let mut found = None;
        while lo < *count && word(OUTPUT_DATA, offset + lo * 68) == cp {
            let row = offset + lo * 68;
            let mut chars = input.chars();
            let mut consumed = 0;
            let mut matched = true;
            for i in 0..8 {
                let expected = word(OUTPUT_DATA, row + i * 4);
                if expected == u32::MAX { break; }
                match chars.next() {
                    Some(ch) if ch as u32 == expected => consumed += ch.len_utf8(),
                    _ => { matched = false; break; }
                }
            }
            if matched && found.is_none_or(|(_, length)| consumed > length) { found = Some((row, consumed)); }
            lo += 1;
        }
        if let Some((row, consumed)) = found {
            let length = word(OUTPUT_DATA, row + 32) as usize;
            let bytes = &OUTPUT_DATA[row + 36..row + 36 + length];
            append_encoded(&mut out, bytes, &name, &mut output_state);
            input = &input[consumed..];
        } else {
            if (fallback == Fallback::Quoted && name != "gsm0338") || name == "iso-2022-kr" {
                use std::io::Write;
                write!(&mut out, "\\x{{{cp:04x}}}").unwrap();
                output_state = 0;
            } else if fallback == Fallback::Nul {
                out.push(0); output_state = 0;
            } else {
                append_encoded(&mut out, substitution, &name, &mut output_state);
            }
            input = &input[c.len_utf8()..];
        }
    }
    Ok(out)
}

fn append_encoded(out: &mut Vec<u8>, mut bytes: &[u8], name: &str, state: &mut u8) {
    let mut next = 0;
    if name == "iso-2022-kr" {
        bytes = bytes.strip_prefix(b"\x1b$)C").unwrap_or(bytes);
        next = u8::from(bytes.first() == Some(&0x0e) && bytes.last() == Some(&0x0f));
        if *state == 1 && next == 1 {
            out.pop(); bytes = &bytes[1..];
        }
    } else if name == "hz" {
        next = u8::from(bytes.starts_with(b"~{") && bytes.ends_with(b"~}"));
        if *state == 1 && next == 1 {
            out.truncate(out.len() - 2); bytes = &bytes[2..];
        }
    } else if matches!(name, "7bit-jis" | "iso-2022-jp" | "iso-2022-jp-1") {
        let designator = [b"\x1b$B".as_slice(), b"\x1b(I".as_slice(), b"\x1b$(D".as_slice()].into_iter().enumerate().find(|(_, seq)| bytes.starts_with(seq));
        if let Some((set, seq)) = designator {
            next = set as u8 + 1;
            if out.ends_with(b"\x1b(B") {
                out.truncate(out.len() - 3);
                if *state == next { bytes = &bytes[seq.len()..]; }
            }
        }
    }
    *state = next;
    out.extend(bytes);
}

fn encode_utf7(text: &str) -> Vec<u8> {
    fn direct(c: char) -> bool {
        // Encode's double-quoted direct set interpolates Perl's $% variable.
        c.is_ascii_alphanumeric() || "\n\r\t '(),-./:?!\"#&*;<=>@[]^_`{|}".contains(c)
    }
    const ALPHABET: &[u8; 64] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
    let mut out = Vec::with_capacity(text.len());
    let mut chars = text.chars().peekable();
    while let Some(c) = chars.next() {
        if direct(c) { out.push(c as u8); continue; }
        if c == '+' && chars.peek().is_none_or(|c| direct(*c)) { out.extend(b"+-"); continue; }
        out.push(b'+');
        let mut bits = 0u32; let mut n = 0;
        let mut current = Some(c);
        while let Some(c) = current {
            let c = if noncharacter(c as u32) { '\u{fffd}' } else { c };
            let mut units = [0; 2];
            for &unit in c.encode_utf16(&mut units).iter() {
                bits = (bits << 16) | u32::from(unit); n += 16;
                while n >= 6 { n -= 6; out.push(ALPHABET[((bits >> n) & 63) as usize]); }
                bits &= (1 << n) - 1;
            }
            current = if chars.peek().is_some_and(|c| !direct(*c)) { chars.next() } else { None };
        }
        if n != 0 { out.push(ALPHABET[((bits << (6 - n)) & 63) as usize]); }
        out.push(b'-');
    }
    out
}

fn base64(bytes: &[u8], out: &mut Vec<u8>) {
    const ALPHABET: &[u8; 64] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
    for chunk in bytes.chunks(3) {
        let bits = (u32::from(chunk[0]) << 16) | (u32::from(*chunk.get(1).unwrap_or(&0)) << 8) | u32::from(*chunk.get(2).unwrap_or(&0));
        out.extend([ALPHABET[(bits >> 18) as usize], ALPHABET[((bits >> 12) & 63) as usize]]);
        out.push(if chunk.len() > 1 { ALPHABET[((bits >> 6) & 63) as usize] } else { b'=' });
        out.push(if chunk.len() > 2 { ALPHABET[(bits & 63) as usize] } else { b'=' });
    }
}

fn encode_mime(text: &str, name: &str, fallback: Fallback) -> Result<Vec<u8>, String> {
    if name == "mime-header-iso_2022_jp" { return encode_mime_jp(text); }
    fn q_direct(b: u8) -> bool { b.is_ascii_alphanumeric() || b" !*+-/".contains(&b) }
    let q = name == "mime-q";
    let mut out = Vec::with_capacity(text.len() * 2);
    let mut chunk = Vec::with_capacity(45);
    let mut payload_len = 0;
    for c in text.chars() {
        let mut utf8 = [0; 16]; let bytes = utf8_scalar(c, fallback, &mut utf8);
        let add = if q { bytes.iter().map(|b| if q_direct(*b) { 1 } else { 3 }).sum() } else { bytes.len() };
        // Encode's B-length estimate deliberately uses floating division, not ceil.
        let exceeds = if q { payload_len + add > 63 } else { (chunk.len() + add + 2) * 4 > 63 * 3 };
        if exceeds { mime_word(&mut out, &chunk, q); chunk.clear(); payload_len = 0; }
        chunk.extend(bytes); payload_len += add;
    }
    if !chunk.is_empty() { mime_word(&mut out, &chunk, q); }
    Ok(out)
}

fn mime_word(out: &mut Vec<u8>, bytes: &[u8], q: bool) {
    if !out.is_empty() { out.extend(b"\r\n "); }
    out.extend(if q { b"=?UTF-8?Q?" } else { b"=?UTF-8?B?" });
    if q {
        const HEX: &[u8; 16] = b"0123456789ABCDEF";
        for &b in bytes {
            if b == b' ' { out.push(b'_'); }
            else if b.is_ascii_alphanumeric() || b"!*+-/".contains(&b) { out.push(b); }
            else { out.extend([b'=', HEX[(b >> 4) as usize], HEX[(b & 15) as usize]]); }
        }
    } else { base64(bytes, out); }
    out.extend(b"?=");
}

fn encode_mime_jp(text: &str) -> Result<Vec<u8>, String> {
    let bytes = encode(text, "euc-jp")?;
    let newline = bytes.last() == Some(&b'\n');
    let trailing_crlf = matches!(bytes.last(), Some(b'\r' | b'\n'));
    let mut words = bytes.split(u8::is_ascii_whitespace).filter(|w| !w.is_empty()).peekable();
    let mut out = Vec::with_capacity(bytes.len() * 2);
    if bytes.first().is_some_and(u8::is_ascii_whitespace) && words.peek().is_some() { out.push(b' '); }
    while let Some(word) = words.next() {
        let mut word = std::borrow::Cow::Borrowed(word);
        if !word.iter().all(|b| (0x21..=0x7e).contains(b)) {
            while words.peek().is_some_and(|w| !w.iter().all(|b| (0x21..=0x7e).contains(b))) {
                let buffer = word.to_mut(); buffer.push(b' '); buffer.extend(words.next().unwrap());
            }
        }
        if word.iter().all(|b| (0x21..=0x7e).contains(b)) {
            let line_len = out.iter().rposition(|b| *b == b'\n').map_or(out.len(), |i| out.len() - i - 1);
            if line_len + word.len() > 76 { out.extend(b"\n "); }
            out.extend(word.as_ref());
        } else {
            let mut input = word.as_ref();
            while !input.is_empty() {
                let leading_cjk = input.starts_with(&[0x8f]) || (input.len() > 1 && (0xa1..=0xfe).contains(&input[0]) && (0xa1..=0xfe).contains(&input[1]));
                if out.len() + 22 + usize::from(leading_cjk) * 8 > 76 {
                    while out.last().is_some_and(u8::is_ascii_whitespace) { out.pop(); }
                    out.extend(b"\n ");
                }
                let line_len = out.iter().rposition(|b| *b == b'\n').map_or(out.len(), |i| out.len() - i - 1);
                let mut end = input.len();
                loop {
                    let unicode = table_decode(&input[..end], "euc-jp")?;
                    let jis = encode(&unicode, "iso-2022-jp")?;
                    let length = 18 + jis.len().div_ceil(3) * 4;
                    if line_len + length <= 76 {
                        out.extend(b"=?ISO-2022-JP?B?"); base64(&jis, &mut out); out.extend(b"?=");
                        input = &input[end..]; break;
                    }
                    let mut previous = 0; let mut i = 0;
                    while i < end { previous = i; i += if input[i] == 0x8f { 3 } else if input[i] == 0x8e || input[i] >= 0xa1 { 2 } else { 1 }; }
                    end = previous;
                }
            }
        }
        let line_len = out.iter().rposition(|b| *b == b'\n').map_or(out.len(), |i| out.len() - i - 1);
        if line_len == 76 { out.extend(b"\n "); } else { out.push(b' '); }
    }
    while out.last() == Some(&b' ') { out.pop(); if out.last() == Some(&b'\n') { out.pop(); } }
    let mut written = 0;
    for i in 0..out.len() {
        if out[i] == b' ' && out.get(i + 1) == Some(&b'\n') { continue; }
        out[written] = out[i]; written += 1;
    }
    out.truncate(written);
    if newline { out.push(b'\n'); }
    if !trailing_crlf && matches!(out.last(), Some(b'\n' | b'\r')) { out.pop(); }
    Ok(out)
}

fn noncharacter(cp: u32) -> bool { (0xfdd0..=0xfdef).contains(&cp) || cp & 0xffff >= 0xfffe }

fn utf8_scalar(c: char, fallback: Fallback, bytes: &mut [u8; 16]) -> &[u8] {
    if !noncharacter(c as u32) { return c.encode_utf8(bytes).as_bytes(); }
    if fallback == Fallback::Default { return '\u{fffd}'.encode_utf8(bytes).as_bytes(); }
    if fallback == Fallback::Nul { bytes[0] = 0; return &bytes[..1]; }
    use std::io::Write;
    let mut remaining = bytes.as_mut_slice();
    write!(&mut remaining, "\\x{{{:04X}}}", c as u32).unwrap();
    let length = 16 - remaining.len();
    &bytes[..length]
}
