[package]
name = "tex-kpse"
version.workspace = true
edition.workspace = true

[dependencies]
ruzstd = { workspace = true }

[build-dependencies]
ruzstd = { workspace = true }
tar = { workspace = true }
ttf-parser = { workspace = true }
[dev-dependencies]
tar = { workspace = true }

[features]
default = ["embed-packages"]
embed-packages = []
