#!/usr/bin/env python3
"""Randomized, byte-exact differential testing against Biber 2.22.

Example (run after building the candidate):
  python scripts/biber_fuzz.py --biber /path/to/biber --seed 222 --count 2000 \
      --jobs 8 --failures-dir /tmp/biber-fuzz-failures

Every index independently generates a new bibliography and document. A seeded
pool of 64 document-control profiles spans styles, options and citation/context
layouts. BCFs are generated by /usr/bin/pdflatex once per exact control profile;
only plain, non-bibliographic prose varies within a profile. Biblatex's first
pass with backend=biber does not read the bibliography. No BBL is reused or
normalized. --no-bcf-cache generates the BCF from every actual document instead.

TeX Live's kpathsea has no getcwd(): it finds the working directory by reading
each ancestor directory and stat()ing its entries, and any entry deleted in
between aborts pdflatex ("pdflatex: NAME: No such file or directory"). Every
child therefore gets a private TMPDIR (Biber creates and removes biber_tmp_XXXX
there), pdflatex runs below a tree that no other worker deletes from, and a
generation aborted by deletions elsewhere in an ancestor (e.g. $HOME) is rerun.

Failures contain both isolated executions, original inputs, BCF provenance,
a complete byte/text difference report and replay metadata. --start INDEX
--count 1 reproduces an index without executing its predecessors. Oracle/oracle
runs exercise this runner, NOT candidate compatibility. Exit codes: 0 match,
1 differences/execution failures, 2 invalid configuration.
"""

import argparse
import concurrent.futures
import difflib
import hashlib
import json
import os
import random
import re
import shutil
import subprocess
import sys
import tempfile
import threading
import time
import uuid
from dataclasses import dataclass
from pathlib import Path

ORACLE = Path("/home/leo/rv-build/biber-oracle/bin/x86_64-linux/biber")
PDFLATEX = Path("/usr/bin/pdflatex")
REPO = Path(__file__).resolve().parent.parent
STYLES = ("authoryear", "authoryear-comp", "authortitle", "authortitle-comp",
          "numeric", "numeric-comp", "alphabetic", "verbose", "apa")
SORTINGS = ("nyt", "nty", "ynt", "ydnt", "anyt", "anyvt", "none", "debug")
WORDS = ("Markets", "Risk", "Evidence", "Networks", "Methods", "Growth",
         "Uncertainty", "Capital", "Trade", "Policy", "Institutions", "Theory")
SPECIALS = ("Über Märkte", "Économie et crédit", "Ångström and Öresund",
            "İstanbul economics", "Łódź and Zürich", "Straße und Maß",
            r"A \& B: 50\%", r"{NASA} and {DNA}", r"{\LaTeX} methods",
            r"Garc{\'i}a and M{\"u}ller", r"Cost\_benefit \#1",
            "Cafe\u0301 and re\u0301sume\u0301", "Nested {Protected {Title}}")
NAMES = ("Ludwig van Beethoven", "de la Cruz, María", "von Neumann, John",
         "van der Waals, Johannes Diderik", "d'Angelo, Lucía", "O'Connor, Sean",
         "Müller, Anna", "Mu\u0308ller, Anna", "Åström, Östen", "İnal, İpek",
         "Łukasiewicz, Jan", "García Márquez, Gabriel", "Smith, Jr., John Paul",
         "Smith, J. P.", "{World Bank}", "{Research and Development Group}",
         r"Garc{\'i}a, Jos{\'e}", r"M{\"u}ller, J{\"o}rg",
         "family=van Gogh, given=Vincent, prefix=van, useprefix=true",
         "family=Curie, given=Marie, given-i=M., suffix=Jr.")


@dataclass(frozen=True)
class Profile:
    options: tuple
    layout: str
    keys: tuple
    context_sorting: str
    labelprefix: str
    per_type: str
    multiple_files: bool


def rng_for(seed, kind, index):
    # Stable independent streams: jobs/count/start never affect generated input.
    digest = hashlib.sha256(f"{seed}:{kind}:{index}".encode("ascii")).digest()
    return random.Random(int.from_bytes(digest, "big"))


def make_profile(seed, index):
    rng = rng_for(seed, "profile", index)
    maxnames = rng.randint(2, 5)
    maxbibnames = rng.randint(2, 6)
    options = {
        "backend": "biber", "style": STYLES[index % len(STYLES)],
        "sorting": rng.choice(SORTINGS),
        "sortlocale": rng.choice(("en_US", "de_DE", "fr_FR", "sv_SE", "tr_TR")),
        "giveninits": rng.choice(("true", "false")),
        "useprefix": rng.choice(("true", "false")),
        "maxnames": str(maxnames), "minnames": str(rng.randint(1, maxnames)),
        "maxbibnames": str(maxbibnames), "minbibnames": str(rng.randint(1, maxbibnames)),
        "uniquename": rng.choice(("false", "init", "full")),
        "uniquelist": rng.choice(("false", "true", "minyear")),
        "mincrossrefs": str(rng.randint(1, 4)),
        "datecirca": rng.choice(("true", "false")),
        "dateuncertain": rng.choice(("true", "false")),
    }
    keys = [f"e{i:02d}" for i in range(1, 9)]
    rng.shuffle(keys)
    return Profile(tuple(sorted(options.items())),
                   rng.choice(("all", "selected", "sections", "segments", "contexts")),
                   tuple(keys[:rng.randint(3, 8)]), rng.choice(SORTINGS[:-1]),
                   rng.choice(("", "A", "B", "X")),
                   rng.choice(("", "book", "article", "incollection")),
                   rng.choice((True, False)))


def render_document(profile, prose):
    options = ",".join(f"{key}={value}" for key, value in profile.options)
    lines = [r"\documentclass{article}", r"\usepackage[T1]{fontenc}",
             r"\usepackage[utf8]{inputenc}", r"\usepackage[english]{babel}",
             rf"\usepackage[{options}]{{biblatex}}"]
    if profile.per_type:
        lines.append(rf"\ExecuteBibliographyOptions[{profile.per_type}]{{maxnames=2,minnames=1}}")
    lines.append(r"\addbibresource{refs.bib}")
    if profile.multiple_files:
        lines.append(r"\addbibresource{extra.bib}")
    lines.extend((r"\begin{document}", prose))
    keys = ",".join(profile.keys)
    first = ",".join(profile.keys[:2])
    rest = ",".join(profile.keys[2:])
    if profile.layout == "sections":
        for selection in (first, rest):
            lines.extend((r"\begin{refsection}", rf"\autocite{{{selection}}}",
                          r"\printbibliography", r"\end{refsection}"))
    elif profile.layout == "segments":
        for selection in (first, rest):
            lines.extend((r"\begin{refsegment}", rf"\autocite{{{selection}}}",
                          r"\end{refsegment}"))
        lines.append(r"\printbibliography")
    else:
        lines.append(rf"\autocite{{{keys}}}")
        if profile.layout in ("all", "contexts"):
            lines.append(r"\nocite{*}")
        lines.append(r"\printbibliography")
        if profile.layout == "contexts":
            context = f"sorting={profile.context_sorting}"
            if profile.labelprefix:
                context += f",labelprefix={profile.labelprefix}"
            lines.extend((rf"\begin{{refcontext}}[{context}]", r"\nocite{*}",
                          r"\printbibliography", r"\end{refcontext}"))
    lines.append(r"\end{document}")
    return "\n".join(lines) + "\n"


def random_title(rng):
    words = rng.sample(WORDS, rng.randint(2, 5))
    if rng.random() < 0.7:
        words.insert(rng.randrange(len(words) + 1), rng.choice(SPECIALS))
    return " ".join(words)


def random_names(rng):
    names = [rng.choice(NAMES) for _ in range(rng.randint(1, 5))]
    if rng.random() < 0.15:
        names.append("others")
    return " and ".join(names)


def random_date(rng):
    year = rng.randint(1600, 2025)
    month = rng.randint(1, 12)
    day = rng.randint(1, 28)
    return rng.choice((str(year), f"{year}-{month:02d}", f"{year}-{month:02d}-{day:02d}",
                       f"{year}/{year + rng.randint(1, 8)}", f"{year}-{month:02d}/..",
                       f"../{year}", f"{year}?", f"{year}~", f"{year}%",
                       f"{year}-2{rng.randint(1, 4)}", f"{year // 10}X",
                       f"{year}-{month:02d}-{day:02d}T12:34:56Z"))


def bib_entry(kind, key, fields):
    return f"@{kind}{{{key},\n" + "".join(
        f"  {field} = {{{value}}},\n" for field, value in fields.items()) + "}\n"


def make_sources(seed, index, profile):
    rng = rng_for(seed, "case", index)
    collision_name = random_names(rng)
    collision_year = str(rng.randint(1950, 2025))
    entries = []
    for number in range(1, rng.randint(9, 17)):
        key = f"e{number:02d}"
        kind = rng.choice(("book", "article", "incollection", "inproceedings",
                           "online", "report", "thesis", "misc", "unpublished"))
        fields = {"title": random_title(rng)}
        if rng.random() < 0.9:
            fields["author"] = collision_name if number <= 2 else random_names(rng)
        if rng.random() < 0.35:
            fields["editor"] = random_names(rng)
        if rng.random() < 0.85:
            fields["date"] = random_date(rng)
        if number <= 2 and rng.random() < 0.7:
            fields["date"] = collision_year
        if rng.random() < 0.3:
            fields["year"] = str(rng.randint(1900, 2025))
            fields["month"] = str(rng.randint(1, 12))
        if rng.random() < 0.4:
            fields["urldate"] = random_date(rng)
        if kind == "article":
            fields["journaltitle"] = random_title(rng)
            fields["volume"] = str(rng.randint(1, 80))
            fields["number"] = str(rng.randint(1, 12))
        if kind in ("book", "report", "thesis"):
            fields["publisher"] = rng.choice(("Oxford Press", "Müller Verlag", "A & B", "Éditions"))
            fields["location"] = rng.choice(("London", "Paris and Zürich", "New York and Berlin"))
        if kind in ("incollection", "inproceedings"):
            fields["crossref"] = "parent"
        if rng.random() < 0.3:
            fields["xdata"] = "shared"
        if rng.random() < 0.6:
            first_page = rng.randint(1, 300)
            fields["pages"] = rng.choice((f"{first_page}--{first_page + rng.randint(1, 50)}",
                                           "iv--xii", "1, 4--9", "100–125"))
        if rng.random() < 0.5:
            fields["keywords"] = rng.choice(("alpha", "beta,alpha", "finance,methods", "β, special"))
        if rng.random() < 0.35:
            fields["doi"] = f"10.{rng.randint(1000, 9999)}/{rng.choice(('a_b', 'test', 'über'))}.{index}.{number}"
            fields["url"] = f"https://example.org/{index}/{number}?a=1&b=two#anchor"
        if rng.random() < 0.2:
            fields[rng.choice(("sorttitle", "shorttitle", "subtitle"))] = random_title(rng)
        if rng.random() < 0.15:
            fields["sortname"] = random_names(rng)
        if rng.random() < 0.15:
            fields["sortyear"] = str(rng.randint(1800, 2030))
        if rng.random() < 0.2:
            fields["langid"] = rng.choice(("english", "german", "french", "spanish"))
        if rng.random() < 0.15:
            fields["options"] = rng.choice(("useprefix=true", "useprefix=false", "skipbib=true"))
        entries.append(bib_entry(kind, key, fields))
    entries.append(bib_entry(rng.choice(("collection", "proceedings")), "parent", {
        "title": random_title(rng), "editor": random_names(rng), "date": random_date(rng),
        "publisher": "Random Press", "location": "Berlin and Paris"}))
    entries.append(bib_entry("xdata", "shared", {
        "publisher": rng.choice(("Shared Press", "Über Verlag")), "edition": str(rng.randint(1, 5))}))
    rng.shuffle(entries)
    if profile.multiple_files:
        split = rng.randint(1, len(entries) - 1)
        sources = {"refs.bib": "\n".join(entries[:split]), "extra.bib": "\n".join(entries[split:])}
    else:
        sources = {"refs.bib": "\n".join(entries)}
    prose = (f"\\section*{{Experiment {index}}}\n"
             + " ".join(rng.choices(WORDS, k=rng.randint(8, 35))) + ".\n")
    sources["main.tex"] = render_document(profile, prose)
    return sources


def resolve_binary(value):
    # Preserve symlink basename: multicall executables select their personality.
    path = Path(shutil.which(value) or value).absolute()
    if not path.is_file() or not os.access(path, os.X_OK):
        raise ValueError(f"Executable not found: {value}")
    return path


def execute(command, directory, timeout):
    started = time.monotonic()
    private = directory.with_name(directory.name + ".tmp")
    private.mkdir()
    environment = dict(os.environ, TMPDIR=str(private))
    try:
        result = subprocess.run(command, cwd=directory, stdout=subprocess.PIPE,
                                stderr=subprocess.PIPE, timeout=timeout, env=environment)
        status = {"command": command, "returncode": result.returncode, "timeout": False}
        stdout, stderr = result.stdout, result.stderr
    except subprocess.TimeoutExpired as error:
        status = {"command": command, "returncode": None, "timeout": True}
        stdout, stderr = error.stdout or b"", error.stderr or b""
    except OSError as error:
        status = {"command": command, "returncode": None, "timeout": False, "error": str(error)}
        stdout, stderr = b"", str(error).encode("utf-8")
    status["seconds"] = round(time.monotonic() - started, 3)
    (directory / "stdout.log").write_bytes(stdout)
    (directory / "stderr.log").write_bytes(stderr)
    (directory / "execution.json").write_text(json.dumps(status, indent=2) + "\n", encoding="utf-8")
    return status


class BcfCache:
    def __init__(self, root, timeout, enabled):
        self.root, self.timeout, self.enabled = root, timeout, enabled
        self.lock = threading.Lock()
        self.futures = {}

    def get(self, profile, sources, case_root):
        key = hashlib.sha256(render_document(profile, "").encode("utf-8")).hexdigest()
        if not self.enabled:
            return self.generate(self.root / case_root.name, sources)
        with self.lock:
            future = self.futures.get(key)
            owner = future is None
            if owner:
                future = concurrent.futures.Future()
                self.futures[key] = future
        if owner:
            try:
                future.set_result(self.generate(self.root / key, sources))
            except Exception as error:
                future.set_exception(error)
        return future.result()

    def generate(self, directory, sources):
        for _ in range(3):
            if directory.exists():
                shutil.rmtree(directory)
                shutil.rmtree(directory.with_name(directory.name + ".tmp"), ignore_errors=True)
            directory.mkdir(parents=True)
            for name, text in sources.items():
                (directory / name).write_text(text, encoding="utf-8")
            status = execute([str(PDFLATEX), "-interaction=nonstopmode", "-halt-on-error",
                              "-no-shell-escape", "main.tex"], directory, self.timeout)
            # kpathsea's readdir-based getcwd raced an unrelated deletion; nothing was compiled.
            raced = status["returncode"] != 0 and re.search(
                rb"^\S*pdflatex: [^\n]*: No such file or directory$", (directory / "stderr.log").read_bytes(), re.M)
            if not raced:
                break
        return directory, status


def difference_report(expected, actual):
    if expected is None or actual is None:
        return f"Missing BBL: oracle={expected is None}, candidate={actual is None}\n"
    if expected == actual:
        return "BBL bytes identical.\n"
    common = min(len(expected), len(actual))
    offset = next((i for i in range(common) if expected[i] != actual[i]), common)
    summary = (f"First differing byte: {offset}; oracle={len(expected)} bytes, "
               f"candidate={len(actual)} bytes\n"
               f"Oracle bytes:    {expected[offset:offset + 100]!r}\n"
               f"Candidate bytes: {actual[offset:offset + 100]!r}\n")
    # Decoding is diagnostic only; equality is always over the original bytes.
    return summary + "".join(difflib.unified_diff(
        expected.decode("utf-8", errors="replace").splitlines(keepends=True),
        actual.decode("utf-8", errors="replace").splitlines(keepends=True),
        fromfile="oracle/main.bbl", tofile="candidate/main.bbl"))


def persist_failure(case_root, run_root, index, metadata, report):
    (case_root / "replay.json").write_text(json.dumps(metadata, indent=2) + "\n", encoding="utf-8")
    (case_root / "difference.txt").write_text(report, encoding="utf-8")
    run_root.mkdir(parents=True, exist_ok=True)
    # Stage beside the destination, so the publish is atomic even across filesystems.
    stage = Path(tempfile.mkdtemp(prefix=f".case-{index:06d}-", dir=run_root))
    try:
        shutil.copytree(case_root, stage, dirs_exist_ok=True)
        destination = run_root / f"case-{index:06d}"
        os.replace(stage, destination)
        return destination
    finally:
        if stage.exists():
            shutil.rmtree(stage)


def run_case(args, index, oracle, candidate, cache, temporary_root, run_root):
    profile = make_profile(args.seed, index % 64)
    sources = make_sources(args.seed, index, profile)
    case_root = temporary_root / "cases" / f"case-{index:06d}"
    case_root.mkdir()
    for name, text in sources.items():
        (case_root / name).write_text(text, encoding="utf-8")
    tex_directory, tex_status = cache.get(profile, sources, case_root)
    bcf = tex_directory / "main.bcf"
    metadata = {
        "seed": args.seed, "index": index, "profile": index % 64,
        "options": dict(profile.options), "oracle_version": "2.22",
        "oracle": str(oracle), "candidate": str(candidate),
        "timeout": args.timeout, "bcf_cache": not args.no_bcf_cache,
        "replay": [sys.executable, str(Path(__file__).absolute()), "--biber", str(candidate),
                   "--oracle", str(oracle), "--seed", str(args.seed), "--start", str(index),
                   "--count", "1", "--timeout", str(args.timeout),
                   "--failures-dir", str(args.failures_dir)],
    }
    if args.no_bcf_cache:
        metadata["replay"].append("--no-bcf-cache")
    if tex_status["returncode"] != 0 or not bcf.is_file():
        if tex_directory != case_root / "tex":
            shutil.copytree(tex_directory, case_root / "tex")
        report = "BCF generation failed; neither Biber execution was compared.\n" + json.dumps(tex_status, indent=2) + "\n"
        destination = persist_failure(case_root, run_root, index, metadata, report)
        return index, "error", str(destination), report.splitlines()[0]
    bcf_bytes = bcf.read_bytes()
    (case_root / "main.bcf").write_bytes(bcf_bytes)
    (case_root / "bcf-origin.tex").write_bytes((tex_directory / "main.tex").read_bytes())
    outputs, statuses = {}, {}
    for label, binary in (("oracle", oracle), ("candidate", candidate)):
        directory = case_root / label
        directory.mkdir()
        for name in sources:
            shutil.copyfile(case_root / name, directory / name)
        (directory / "main.bcf").write_bytes(bcf_bytes)
        statuses[label] = execute([str(binary), "main"], directory, args.timeout)
        output = directory / "main.bbl"
        outputs[label] = output.read_bytes() if output.is_file() else None
    execution_failed = any(status["returncode"] != 0 for status in statuses.values())
    equal = outputs["oracle"] is not None and outputs["oracle"] == outputs["candidate"]
    if equal and not execution_failed:
        shutil.rmtree(case_root)
        return index, "pass", None, None
    report = difference_report(outputs["oracle"], outputs["candidate"])
    report += "\nExecution diagnostics:\n" + json.dumps(statuses, indent=2) + "\n"
    for label in ("oracle", "candidate"):
        directory = case_root / label
        for log in ("stdout.log", "stderr.log", "main.blg"):
            path = directory / log
            if path.is_file():
                report += f"\n--- {label}/{log} ---\n" + path.read_text(encoding="utf-8", errors="replace")
    destination = persist_failure(case_root, run_root, index, metadata, report)
    return index, "error" if execution_failed else "mismatch", str(destination), report.splitlines()[0]


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--biber", required=True, help="Candidate Biber executable")
    parser.add_argument("--oracle", default=str(ORACLE), help="Oracle executable; must report Biber 2.22")
    parser.add_argument("--seed", type=int, default=222, help="Deterministic generation seed (default: 222)")
    parser.add_argument("--count", type=int, default=2000, help="Number of independent random documents (default: 2000)")
    parser.add_argument("--start", type=int, default=0, help="First case index, for independent replay")
    parser.add_argument("--jobs", type=int, default=1, help="Concurrent isolated documents (default: 1)")
    parser.add_argument("--timeout", type=int, default=120, help="Per-process timeout in seconds")
    parser.add_argument("--failures-dir", type=Path, default=Path(tempfile.gettempdir()) / "biber-fuzz-failures",
                        help="Failure storage outside the repository")
    parser.add_argument("--no-bcf-cache", action="store_true", help="Generate BCF afresh for every actual document")
    args = parser.parse_args()
    if args.count < 1 or args.start < 0 or args.jobs < 1 or args.timeout < 1:
        parser.error("count, jobs and timeout must be positive; start must be nonnegative")
    args.failures_dir = args.failures_dir.expanduser().resolve()
    if args.failures_dir == REPO or REPO in args.failures_dir.parents:
        parser.error("--failures-dir must be outside the repository")
    try:
        oracle, candidate = resolve_binary(args.oracle), resolve_binary(args.biber)
        if not PDFLATEX.is_file():
            raise ValueError(f"BCF generation requires {PDFLATEX}")
        version = subprocess.run([str(oracle), "--version"], stdout=subprocess.PIPE,
                                 stderr=subprocess.PIPE, timeout=args.timeout)
        if version.returncode or version.stdout.strip() != b"biber version: 2.22":
            raise ValueError(f"Expected Biber 2.22 oracle, got {version.stdout!r} {version.stderr!r}")
    except (OSError, ValueError, subprocess.TimeoutExpired) as error:
        parser.error(str(error))
    run_root = args.failures_dir / f"seed-{args.seed}-{uuid.uuid4().hex[:12]}"
    print(f"seed={args.seed} count={args.count} start={args.start} jobs={args.jobs} oracle=2.22", flush=True)
    if oracle.samefile(candidate):
        print("Runner mechanics smoke: oracle and candidate are the same executable; NOT compatibility acceptance.", flush=True)
    totals = {"pass": 0, "mismatch": 0, "error": 0}
    with tempfile.TemporaryDirectory(prefix="biber-fuzz-") as temporary:
        root = Path(temporary)
        (root / "cases").mkdir()
        cache = BcfCache(root / "bcf-cache", args.timeout, not args.no_bcf_cache)
        with concurrent.futures.ThreadPoolExecutor(max_workers=args.jobs) as pool:
            futures = {pool.submit(run_case, args, index, oracle, candidate, cache, root, run_root): index
                       for index in range(args.start, args.start + args.count)}
            for future in concurrent.futures.as_completed(futures):
                index = futures[future]
                try:
                    index, outcome, destination, detail = future.result()
                except Exception as error:
                    # Infrastructure exceptions still retain the inputs that were reached.
                    outcome = "error"
                    case_root = root / "cases" / f"case-{index:06d}"
                    case_root.mkdir(exist_ok=True)
                    detail = f"Runner error: {type(error).__name__}: {error}"
                    metadata = {"seed": args.seed, "index": index, "oracle": str(oracle),
                                "candidate": str(candidate), "error": detail}
                    destination = persist_failure(case_root, run_root, index, metadata, detail + "\n")
                totals[outcome] += 1
                if outcome != "pass":
                    print(f"{outcome.upper()} index={index}: {detail}\n  saved: {destination}", flush=True)
    mismatches = totals["mismatch"] + totals["error"]
    print(f"SUMMARY seed={args.seed} count={args.count} start={args.start} "
          f"mismatches={mismatches} byte_mismatches={totals['mismatch']} "
          f"errors={totals['error']} passed={totals['pass']}", flush=True)
    if mismatches:
        print(f"Failures: {run_root}", flush=True)
    return 1 if mismatches else 0


if __name__ == "__main__":
    sys.exit(main())
