#!/usr/bin/env python3
"""Build real native-font fixtures from the hash-pinned IPAex upstream archive."""
import argparse
import hashlib
import io
import json
import tarfile
from pathlib import Path
from copy import deepcopy

from fontTools import subset
from fontTools.ttLib import TTCollection, TTFont
from fontTools.ttLib.tables._c_m_a_p import CmapSubtable

ROOT = Path(__file__).resolve().parent.parent
FIXTURES = ROOT / "scripts" / "fixtures" / "fonts"


def make_face(data: bytes, name: str, characters: set[int]) -> TTFont:
    font = TTFont(io.BytesIO(data), recalcTimestamp=False)
    options = subset.Options()
    options.retain_gids = True  # Exercise the original glyph IDs above 255.
    options.notdef_outline = True
    options.name_IDs = [0, 1, 2, 3, 4, 5, 6, 13, 14, 16, 17]
    options.name_legacy = True
    options.name_languages = [0x409]
    sub = subset.Subsetter(options=options)
    sub.populate(unicodes=characters)
    sub.subset(font)
    # IPA's modified-font condition forbids reuse of the upstream font name.
    for record in font["name"].names:
        if record.nameID in (1, 3, 4, 6, 16):
            record.string = name.encode(record.getEncoding())
        elif record.nameID in (2, 17):
            record.string = "Regular".encode(record.getEncoding())
    font["head"].created = font["head"].modified = 3786912000
    return font


def generate(archive_path: Path) -> None:
    lock = json.loads((ROOT / "crates/tex-kpse/assets/packages.lock.json").read_text())
    package = lock["packages"]["ipaex"]
    with archive_path.open("rb") as source:
        if hashlib.file_digest(source, "sha256").hexdigest() != package["upstream_sha256"]:
            raise ValueError("IPAex archive does not match the pinned upstream SHA256")
    font_path = "fonts/truetype/public/ipaex/ipaexm.ttf"
    with tarfile.open(archive_path, "r:xz") as archive:
        data = archive.extractfile(font_path).read()
    if hashlib.sha256(data).hexdigest() != package["files"][font_path]:
        raise ValueError("IPAex font does not match the locked font SHA256")
    cases = ("unicode_supplementary", "unioned_subsets", "cache_invalidation",
             "truetype_collection", "error_bad_font_index", "error_restricted_font",
             "error_unavailable_style")
    characters = set(range(32, 127))
    characters.update((0x2013, 0x2014, 0x2018, 0x2019, 0x201C, 0x201D))
    for case in cases:
        characters.update(map(ord, (FIXTURES / case / "main.tex").read_text()))
    # Supplementary test deliberately maps mathematical letters to real Latin outlines.
    characters.difference_update(range(0x1D400, 0x1D404))
    font_specs = (("unioned_subsets", "shared.ttf", "RatexSharedMincho"),
                  ("cache_invalidation", "dynamic.ttf", "RatexDynamicMincho"),
                  ("error_unavailable_style", "dynamic.ttf", "RatexDynamicMincho"),
                  ("error_restricted_font", "restricted.ttf", "RatexRestrictedMincho"))
    for case, filename, name in font_specs:
        font = make_face(data, name, characters)
        if case == "error_restricted_font":
            font["OS/2"].fsType = 2
        font.save(FIXTURES / case / filename)
    astral = make_face(data, "RatexSupplementaryMincho", characters)
    cmap = CmapSubtable.newSubtable(12)
    cmap.platformID, cmap.platEncID, cmap.language = 3, 10, 0
    cmap.cmap = astral.getBestCmap().copy()
    order = list(astral.getGlyphOrder())
    for i in range(4):
        original = cmap.cmap[ord("A") + i]
        name = f"ratexAstral{i}"
        astral["glyf"][name] = deepcopy(astral["glyf"][original])
        astral["hmtx"][name] = astral["hmtx"][original]
        if "vmtx" in astral:
            astral["vmtx"][name] = astral["vmtx"][original]
        order.append(name)
        cmap.cmap[0x1D400 + i] = name
    astral.setGlyphOrder(order)
    astral["cmap"].tables = [table for table in astral["cmap"].tables if table.format != 12]
    astral["cmap"].tables.append(cmap)
    astral.save(FIXTURES / "unicode_supplementary/supplementary.ttf")
    collection = TTCollection()
    collection.fonts = [make_face(data, f"CollectionFace{n}", characters) for n in ("Zero", "One")]
    one = collection.fonts[1]
    a = one.getBestCmap()[ord("A")]
    width, bearing = one["hmtx"][a]
    one["hmtx"][a] = (width + 100, bearing)
    for case in ("truetype_collection", "error_bad_font_index"):
        collection.save(FIXTURES / case / "collection.ttc")
    license_text = (ROOT / "crates/tex-kpse/assets/legal/IPA_Font_License_Agreement_v1.0.txt").read_text()
    for case in cases:
        (FIXTURES / case / "LICENSE-IPA.txt").write_text(
            "Modified and renamed IPAex fixture; generated by scripts/generate_font_fixtures.py.\n"
            + "Original pinned source and replacement fonts: https://moji.or.jp/ipafont/\n\n"
            + license_text)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("archive", type=Path, help="locked ipaex.tar.xz (no host font lookup)")
    generate(parser.parse_args().archive)
