#!/usr/bin/env python3
"""Extract Unicode::Collate 1.31 tables from Biber's unpacked PAR payload.

Writes OUTPUT (a small Rust index) and OUTPUT with suffix .bin, which holds one
zlib stream per table so a run inflates only the tables it uses. Inflated, a
table is little-endian: row count (u32); per row, sequence length and element
count (u8 each); all sequences (u32); all collation elements (5 x u16). Rows are
sorted by sequence. TABLES gives each stream's (offset, length) in the .bin.
"""
import argparse
import pathlib
import re
import struct
import zlib

p = argparse.ArgumentParser()
p.add_argument('collate', type=pathlib.Path, help='PAR inc/lib/Unicode/Collate directory')
p.add_argument('output', type=pathlib.Path, help='Rust index; the blob is written beside it as .bin')
a = p.parse_args()
streams = []
elements = 0

def entries(text):
    out = {}
    for line in text.splitlines():
        m = re.match(r'^([0-9A-Fa-f ]+)\s*;\s*(.*?)\s*(?:#.*)?$', line)
        if not m:
            continue
        seq = tuple(int(x, 16) for x in m[1].split())
        ces = []
        for mark, body in re.findall(r'\[([.*])([^\]]+)\]', m[2]):
            w = [int(x, 16) for x in body.split('.')]
            w += [0] * (4-len(w))
            ces.append((*w, int(mark == '*')))
        if ces:
            out[seq] = ces if any(any(w[:3]) for w in ces) else []
    return out

def table(data):
    global elements
    rows = sorted(data.items())
    assert all(len(seq) < 256 and len(ws) < 256 for seq, ws in rows)
    seqs = [c for seq, _ in rows for c in seq]
    ws = [x for _, w in rows for e in w for x in e]
    elements += len(ws) // 5
    blob = struct.pack('<I', len(rows)) + bytes(n for seq, w in rows for n in (len(seq), len(w)))
    blob += struct.pack(f'<{len(seqs)}I{len(ws)}H', *seqs, *ws)
    streams.append(zlib.compress(blob, 9))
    return len(streams) - 1

text = '// Generated by scripts/generate_biber_collation.py from Biber 2.22 PAR: Unicode::Collate 1.31, DUCET 13.0.0, locale 1.31.\n// Unicode data copyright Unicode, Inc.; https://www.unicode.org/license.txt\n'
text += f'const DUCET: usize = {table(entries((a.collate/"allkeys.txt").read_text()))};\n'
locales = []
for f in sorted((a.collate/'Locale').glob('*.pl')):
    src = f.read_text()
    data = entries(src)
    cjk_data = {}
    cjk = re.search(r'CJK::(\w+)::weight', src)
    if cjk:
        cjk_src = (a.collate/'CJK'/f'{cjk[1]}.pm').read_text()
        body = cjk_src.split('__DATA__\n')[1].split('__END__')[0]
        if cjk[1] == 'Korean':
            prims = dict((x, int(y,16)) for x,y in re.findall(r"'([0-9A-F]+)',\s*0x([0-9A-Fa-f]+)", cjk_src))
            prim = []
            for line in body.splitlines():
                if ':' in line:
                    prim = [prims[x] for x in line.split(':')[1].split('-')]
                    secondary = 0x20
                else:
                    for cp in line.split():
                        secondary += 1
                        u = int(cp,16)
                        cjk_data[(u,)] = [(prim[0],secondary,2,u & 0xffff,0)] + [(x,0x20,2,u & 0xffff,0) for x in prim[1:]]
        else:
            wt = int(re.search(r'my \$wt = 0x([0-9A-Fa-f]+)', cjk_src)[1],16)
            for token in body.split():
                if '-' not in token:
                    u = int(token,16)
                    cjk_data[(u,)] = [(wt,0x20,2,u & 0xffff,0)]
                wt += 1
    locale_rows = table(data)
    cjk_rows = table(cjk_data)
    backwards = re.search(r'backwards\s*=>\s*(\d+)',src)
    suppress = re.search(r'suppress\s*=>\s*\[([^\]]+)\]',src)
    suppress_values = suppress[1] if suppress else ''
    upper = bool(re.search(r'upper_before_lower\s*=>\s*1',src))
    locales.append(f'("{f.stem}", {locale_rows}, {backwards[1] if backwards else 0}, {str(upper).lower()}, &[{suppress_values}], {cjk_rows})')
text += 'static LOCALES: &[(&str, usize, u8, bool, &[u32], usize)] = &[\n' + ',\n'.join(locales) + '\n];\n'
offset = 0
ranges = []
for s in streams:
    ranges.append(f'({offset}, {len(s)})')
    offset += len(s)
text += 'const TABLES: &[(usize, usize)] = &[\n' + ',\n'.join(ranges) + '\n];\n'
a.output.with_suffix('.bin').write_bytes(b''.join(streams))
a.output.write_text(text)
print(f'{len(locales)} locale tables; {elements} collation elements; {offset} compressed bytes')
