#!/usr/bin/env python3
"""Generate regex tables from Biber 2.22's extracted Perl unicore directory."""
import argparse
import json
from pathlib import Path
import re


def generate(source: Path, output: Path):
    version = (source / 'version').read_text().strip()
    if version != '15.0.0':
        raise ValueError(f'expected bundled Unicode 15.0.0, got {version}')
    ucd = (source / 'UCD.pl').read_text()

    def section(name):
        return re.search(r'%Unicode::UCD::' + name + r' = \((.*?)\n\);', ucd, re.S).group(1)

    def mapping(name):
        return dict(re.findall(r"'([^']*)' => '([^']*)'", section(name)))

    inline = re.findall(r"'([^']*)'", re.search(r'@Unicode::UCD::inline_definitions = \((.*?)\n\);', ucd, re.S).group(1))
    tables = []
    ids = {}
    files = {}

    def table_id(file):
        if file in files:
            return files[file]
        invert = file.startswith('!')
        base = file.lstrip('!')
        if base.startswith('#/'):
            invert ^= base[2:].startswith('!')
            data = inline[int(base[2:].lstrip('!'))]
        else:
            data = re.search(r"return <<'END';\n(.*?)\nEND(?:\n|$)", (source / 'lib' / (base + '.pl')).read_text(), re.S).group(1)
        numbers = list(map(int, data.splitlines()[1:]))
        if len(numbers) % 2:
            numbers.append(0x110000)
        ranges = tuple((a, min(b - 1, 0x10ffff)) for a, b in zip(numbers[::2], numbers[1::2]) if a < 0x110000 and a < b)
        if invert:
            complement = []
            start = 0
            for a, b in ranges:
                if start < a:
                    complement.append((start, a - 1))
                start = b + 1
            if start <= 0x10ffff:
                complement.append((start, 0x10ffff))
            ranges = tuple(complement)
        if ranges not in ids:
            ids[ranges] = len(tables)
            tables.append(ranges)
        files[file] = ids[ranges]
        return files[file]

    loose = mapping('loose_to_file_of')
    strict = mapping('stricter_to_file_of')
    caseless = mapping('caseless_equivalent')
    aliases = {k: table_id(v) for k, v in {**strict, **loose}.items()}
    case_aliases = {k: table_id(v) for k, v in caseless.items()}
    lines = ['// Generated by scripts/generate_biber_perl_unicode.py.', '// Source: Biber 2.22 PAR, Perl 5.38.2, Unicode 15.0.0; do not use host Unicode tables.', 'pub(super) const TABLES: &[&[(u32, u32)]] = &[']
    for ranges in tables:
        lines.append('    &[' + ', '.join(f'(0x{a:X}, 0x{b:X})' for a, b in ranges) + '],')
    lines.append('];')
    for name, values in [('PROPERTIES', aliases), ('CASE_PROPERTIES', case_aliases)]:
        lines.append(f'pub(super) const {name}: &[(&str, usize)] = &[')
        lines.extend(f'    ({json.dumps(k)}, {v}),' for k, v in sorted(values.items()))
        lines.append('];')
    special = ['word', 'digit', 'space', '_perl_quotemeta', 'extpict',
               'gcb=control', 'gcb=cr', 'gcb=lf', 'gcb=extend', 'gcb=zwj', 'gcb=regionalindicator',
               'gcb=prepend', 'gcb=spacingmark', 'gcb=l', 'gcb=v', 'gcb=t', 'gcb=lv', 'gcb=lvt']
    for name in special:
        constant = name.upper().replace('=', '_').lstrip('_')
        lines.append(f'pub(super) const {constant}: &[(u32, u32)] = TABLES[{aliases[name]}];')
    props = mapping('loose_property_name_of')
    lines.append('pub(super) const PROPERTY_NAMES: &[(&str, &str)] = &[')
    lines.extend(f'    ({json.dumps(k)}, {json.dumps(v)}),' for k, v in sorted(props.items()))
    lines.append('];')
    for name in ['Cf', 'Uc', 'Lc', 'Tc']:
        content = (source / 'To' / (name + '.pl')).read_text()
        folds = {}
        body = re.search(r"return <<'END';\n(.*?)\nEND(?:\n|$)", content, re.S).group(1)
        for row in body.splitlines():
            first, last, target = row.split('\t')
            a, b, c = int(first, 16), int(last or first, 16), int(target, 16)
            for point in range(a, b + 1):
                folds[point] = [c + point - a]
        for cp, target in re.findall(r'# U\+([0-9A-F]+) => ([0-9A-F ]+)', content):
            folds[int(cp, 16)] = [int(x, 16) for x in target.split()]
        lines.append(f'pub(super) const {name.upper()}: &[(char, &[char])] = &[')
        for cp, target in sorted(folds.items()):
            if target != [cp]:
                chars = ', '.join("'\\u{" + f'{x:X}' + "}'" for x in target)
                lines.append("    ('\\u{" + f'{cp:X}' + "}', &[" + chars + ']),')
        lines.append('];')
    names = {}
    name_body = re.search(r"return <<'END';\n(.*?)\nEND(?:\n|$)", (source / 'Name.pl').read_text(), re.S).group(1)
    for row in name_body.strip().split('\n\n'):
        point, name = row.split('\n', 1)
        names[name] = ''.join(chr(int(x, 16)) for x in point.split())
    # Hangul names are algorithmic and absent from Name.pl.
    lead = ['G','GG','N','D','DD','R','M','B','BB','S','SS','','J','JJ','C','K','T','P','H']
    vowel = ['A','AE','YA','YAE','EO','E','YEO','YE','O','WA','WAE','OE','YO','U','WEO','WE','WI','YU','EU','YI','I']
    tail = ['','G','GG','GS','N','NJ','NH','D','L','LG','LM','LB','LS','LT','LP','LH','M','B','BS','S','SS','NG','J','C','K','T','P','H']
    for index in range(11172):
        names['HANGUL SYLLABLE ' + lead[index // 588] + vowel[index // 28 % 21] + tail[index % 28]] = chr(0xac00 + index)
    lines.append('pub(super) const NAMES: &[(&str, &str)] = &[')
    for name, value in sorted(names.items()):
        escaped = ''.join('\\u{' + f'{ord(c):X}' + '}' for c in value)
        lines.append(f'    ({json.dumps(name)}, "{escaped}"),')
    lines.append('];')
    algorithmic = (source / 'Name.pm').read_text().split('my %names_ending_in_code_point = (', 1)[1].split('    );', 1)[0]
    lines.append('pub(super) const ALGORITHMIC_NAMES: &[(&str, &[(u32, u32)])] = &[')
    for name, high, low in re.findall(r"'([^']*)' =>\s*\{\s*'high' =>\s*\[(.*?)\],\s*'low' =>\s*\[(.*?)\]", algorithmic, re.S):
        highs = list(map(int, re.findall(r'\d+', high)))
        lows = list(map(int, re.findall(r'\d+', low)))
        ranges = ', '.join(f'(0x{a:X}, 0x{b:X})' for a, b in zip(lows, highs))
        lines.append(f'    ({json.dumps(name)}, &[{ranges}]),')
    lines.append('];')
    def value_rows(name):
        content = (source / 'To' / (name + '.pl')).read_text()
        body = re.search(r"return <<'END';\n(.*?)\nEND(?:\n|$)", content, re.S).group(1)
        return [(int(a, 16), int(b or a, 16), value) for a, b, value in (row.split('\t') for row in body.splitlines())]

    for name in ['WB', 'SB']:
        lines.append(f'pub(super) const {name}_RANGES: &[(u32, u32, &str)] = &[')
        for a, b, value in value_rows(name):
            lines.append(f'    (0x{a:X}, 0x{b:X}, {json.dumps(value)}),')
        lines.append('];')
    scripts = value_rows('_PerlSCX')
    script_names = sorted({v for _, _, values in scripts for v in values.split()} - {'Common', 'Inherited', 'Unknown'})
    assert len(script_names) <= 256
    script_ids = {name: i for i, name in enumerate(script_names)}
    lines.append('pub(super) const SCRIPT_RANGES: &[(u32, u32, u8, [u64; 4])] = &[')
    for a, b, value in scripts:
        kind = {'Common': 1, 'Inherited': 1, 'Unknown': 0}.get(value, 2)
        bits = [0] * 4
        for name in value.split():
            if name in script_ids:
                i = script_ids[name]
                bits[i // 64] |= 1 << (i % 64)
        mask = ', '.join(f'0x{x:X}' for x in bits)
        lines.append(f'    (0x{a:X}, 0x{b:X}, {kind}, [{mask}]),')
    lines.append('];')
    output.write_text('\n'.join(lines) + '\n')
    print(f'{len(tables)} property tables, {len(aliases)} aliases, {len(names)} names; {output.stat().st_size} bytes')


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('unicore', type=Path)
    parser.add_argument('output', type=Path)
    args = parser.parse_args()
    generate(args.unicore, args.output)
