#!/usr/bin/perl
# Generate exact Encode mappings; runtime decoding has no Perl dependency.
# Use Encode-3.20 CPAN release (SHA256 ced8fc06c54c05f227bfd9db38c1ed48a5a295db89f497d42b335afbf1f73517):
# perl Makefile.PL && make; perl -I/path/Encode-3.20/blib/lib -I/path/Encode-3.20/blib/arch scripts/generate-biber-encoding.pl .
use strict; use warnings; use Encode qw(decode encode FB_CROAK LEAVE_SRC find_encoding); use Encode::Alias;
die "Biber 2.22 requires Encode 3.20; use its isolated blib/lib and blib/arch\n" unless $Encode::VERSION eq '3.20';
my $root = shift // '.';
my $dir = "$root/crates/tex-biber/src";
open my $data, '>:raw', "$dir/encoding_tables.bin" or die $!;
open my $index, '>', "$dir/encoding_tables.rs" or die $!;
open my $encoded, '>:raw', "$dir/encoding_output_tables.bin" or die $!;
my @output_index; my @substitutions; my $output_offset=0;
sub output_table {
 my ($name,$inputs)=@_;
 push @substitutions,'    ("'.lc($name).'", &['.join(',',unpack('C*',encode($name,chr(0x10ffff))))."]),\n";
 my @output;
 for my $input (sort { join('',map{sprintf '%08x',ord}split//,$a) cmp join('',map{sprintf '%08x',ord}split//,$b) } keys %$inputs) {
   my $bytes=eval{encode($name,$input,FB_CROAK|LEAVE_SRC)};
   next if $@;
   next if $name eq 'iso-2022-kr' && $bytes =~ /\\x\{/;
   my @cp=map{ord}split//,$input;
   die "$name encoded output too long" if length($bytes)>32;
   push @output,pack('V9',@cp,(0xffffffff)x(8-@cp),length($bytes)).pack('a32',$bytes);
 }
 print $encoded @output;
 push @output_index,'    ("'.lc($name).'", '.$output_offset.', '.scalar(@output)."),\n";
 $output_offset+=68*@output;
}
print $index "// Generated by scripts/generate-biber-encoding.pl using Perl Encode $Encode::VERSION.\nconst TABLES: &[(&str, usize, usize)] = &[\n";
my @names = Encode->encodings(':all'); my $offset=0;
for my $name (@names) {
 next if $name =~ /^(?:UTF|UCS|utf|iso-2022|7bit-jis|hz|MIME)/;
 my $multi = $name =~ /^(?:shiftjis|big5|cp93[269]|cp949|cp950|euc|gb.*raw|iso-ir|jis020[128]-raw|jis0212-raw|johab|ksc|Mac(?:Chinese|Japanese|Korean)|gsm)/;
 my @rows;
 my $add = sub { my ($key,$bytes)=@_; my $copy=$bytes; my $out=eval{decode($name,$copy,FB_CROAK)}; return if $@ || length($copy) || !length($out); my @cp=map{ord}split//,$out; die "$name output too long" if @cp>8; return if grep{$_>0x10ffff || ($_>=0xd800 && $_<=0xdfff)}@cp; push @rows,pack('V9',$key,@cp,(0xffffffff)x(8-@cp)); };
 for (0..255) {$add->(0x1000000|$_,pack('C',$_));}
 if ($multi) {for my $a (0..255) {for my $b (0..255) {$add->(0x2000000|($a<<8)|$b,pack('CC',$a,$b));}}}
 if ($name eq 'euc-jp') {for my $a (0xa1..0xfe) {for my $b (0xa1..0xfe) {$add->(0x38f0000|($a<<8)|$b,pack('CCC',0x8f,$a,$b));}}}
 # Retain only atomic sequences, not two separately decoded characters.
 my %single=map{unpack('V',$_)&255=>1}grep{(unpack('V',$_)>>24)==1}@rows;
 @rows=grep{my $k=unpack('V',$_); ($k>>24)==1 || !exists($single{($k>>8)&255})}@rows;
 print $data @rows; print $index '    ("'.lc($name).'", '.$offset.', '.scalar(@rows)."),\n"; $offset+=36*@rows;
 my %input=map { chr($_)=>1 } (0..0xd7ff,0xe000..0xffff);
 for my $row (@rows) { my @cp=unpack('V9',$row); shift @cp; @cp=grep{$_!=0xffffffff}@cp; $input{join('',map{chr}@cp)}=1; }
 output_table($name,\%input);
}
for my $name ('hz','7bit-jis','iso-2022-jp','iso-2022-jp-1','iso-2022-kr') {
 my %input=map { chr($_)=>1 } (0..0xd7ff,0xe000..0xffff);
 if ($name =~ /jis|jp/) {
   for my $a (0xff61..0xff9f) {for my $b (0xff9e,0xff9f) {$input{chr($a).chr($b)}=1;}}
 }
 output_table($name,\%input);
}
print $index "];\n";
print $index "const ENCODE_TABLES: &[(&str, usize, usize)] = &[\n",@output_index,"];\n";
print $index "const ENCODE_SUBSTITUTIONS: &[(&str, &[u8])] = &[\n",@substitutions,"];\n";
