lfs.mkdir("fio_unicode_mime") lfs.chdir("fio_unicode_mime")
local function T(t) if not t then return "nil" end local r={} for i,v in ipairs(t) do r[#r+1]=tostring(v) end return "{"..table.concat(r,",").."}" end
local data = "\1\2\3\4\255\254\253\252\128\0\64\0\0\1\0\0\200\100\50\25\10\5\2\1ABC\nline two\r\nlast"
local f=io.open("bin.dat","wb") f:write(data) f:close()
f=io.open("bin.dat","rb")
P(fio.readcardinal1(f), fio.readcardinal2(f), fio.readcardinal3(f), fio.getposition(f))
P(fio.readinteger1(f), fio.readinteger2(f), fio.readinteger3(f), fio.getposition(f))
fio.setposition(f,0) P(fio.readcardinal4(f), fio.readcardinal4le(f), fio.readinteger4(f), fio.readinteger4le(f))
fio.setposition(f,0) P(fio.readcardinal2le(f), fio.readcardinal3le(f), fio.readinteger2le(f), fio.readinteger3le(f), fio.readcardinal1le and fio.readcardinal1le(f), fio.readinteger1le(f))
fio.setposition(f,0) P(T(fio.readcardinaltable(f,4,1)), T(fio.readcardinaltable(f,2,2)), T(fio.readintegertable(f,2,1)), T(fio.readintegertable(f,1,3)))
fio.setposition(f,8) P(fio.readfixed2(f), fio.readfixed4(f), fio.read2dot14(f))
fio.setposition(f,0) fio.skipposition(f,3) P(fio.getposition(f), fio.readbytes(f,3))
fio.setposition(f,4) P(T(fio.readbytetable(f,4)), fio.readbytes(f,2))
fio.setposition(f,26) P(fio.readline(f)) P(fio.readline(f)) P(fio.readline(f)) P(fio.readline(f))
fio.setposition(f,#data-1) P(fio.readcardinal2(f), fio.readcardinal4(f), fio.readbytes(f,5), fio.readinteger1(f))
fio.setposition(f,#data+10) P(fio.readcardinal1(f), fio.getposition(f))
P((pcall(fio.readcardinal1,"x")))
P((pcall(fio.readcardinal1)))
P(sio and sio.readcardinal2("\1\2\3",1), sio and sio.readcardinal2("\1\2\3",5))
P(sio and sio.readcardinaltable and T(sio.readcardinaltable("\1\2\3\4",2,2)))
f:close()
P(pcall(fio.readcardinal1,f))
os.remove("bin.dat")
-- unicode
local u=unicode.utf8
P(u.len("aä€😀"), u.sub("aä€😀",2,3), u.upper("äbc"), u.lower("ÄBC"), u.reverse("aä€"), u.byte("ä€",1,-1))
P(u.char(97,228,8364,128512), u.rep("ä",3,"-"), u.find("aä€x","€"), u.match("hello wörld","%a+$"), u.gsub("äöü","ö","o"))
P(u.format("%s|%5s|%q", "ä", "€", "x\n"))
for w in u.gmatch("ä b €","%S+") do P("g",w) end
P(unicode.ascii.upper("äabc"), unicode.latin1.upper("\228abc") == "\196ABC", unicode.latin1.char(228)=="\228", unicode.latin1.len("\228"))
P(unicode.grapheme.len("e\204\129a"), unicode.grapheme.sub("e\204\129ab",1,1)=="e\204\129")
P(u.find("aä€x","%a",3), u.match("äö","(.)(.)"), u.find("a.b",".",1,true), u.len("\255"))
P(pcall(u.char,-1)) P(pcall(u.sub))
P(u.match("Ünï","%u"), u.match("ünï","%l+"), u.match("日本語","%a+"), u.find("日本語","本"))
P(u.byte("日",1), u.byte("日本語",2), u.sub("日本語",-2), u.sub("日本語",2,-2), u.dump and type(u.dump))
-- mime
P(mime.b64("hello wor"), mime.unb64("aGVsbG8gd29y"), mime.b64("hello", "xx"))
P(mime.qp("ä=b\n"), mime.unqp("=C3=A4=3Db"), mime.eol(0,"a\nb\r\nc"), mime.dot(2,"a\r\n.b"))
P(mime.wrp(0,"abcdefgh",4), mime.qpwrp(0,"abcdefghij",4))
P(mime.encode("base64")("hello"), mime.decode("base64")("aGVsbG8="), mime.normalize("\r\n")("a\nb"))
P(ltn12.filter.chain(mime.encode("base64"),mime.wrap("base64",8))("0123456789abcdef"))
local sink, getres = (function() local t={} return function(c) if c then t[#t+1]=c end return 1 end, function() return table.concat(t) end end)()
ltn12.pump.all(ltn12.source.string("hello world"), sink) P(getres())
P(ltn12._VERSION, mime._VERSION, ltn12.BLOCKSIZE)

