lfs.mkdir("hash_zlib") lfs.chdir("hash_zlib")
local function hex(s) return (s:gsub(".", function(c) return string.format("%02x", c:byte()) end)) end
P(hex(md5.sum("abc")), md5.sumhexa("abc"), md5.sumHEXA("abc"), hex(md5.exor("abc","xyz")))
P(pcall(md5.exor,"a","bb"))
local c = md5.crypt("hello world","key","seed") P(hex(c), md5.decrypt(c,"key"))
P(hex(sha2.digest256("abc")))
P(hex(sha2.digest384("abc")))
P(hex(sha2.digest512("abc")))
P(zlib.version(), zlib.crc32(), zlib.crc32(0,"abc"), zlib.adler32(), zlib.adler32(1,"abc"), zlib.crc32(zlib.crc32(0,"ab"),"c"))
local z=zlib.compress("hello hello hello hello") P(hex(z), zlib.decompress(z))
P(hex(zlib.compress("abc",1)), hex(zlib.compress("abc",9)), hex(zlib.compress("")))
P(pcall(zlib.decompress,"garbage"))
P(pcall(zlib.decompress,string.sub(z,1,5)))
local co=zlib.compressobj(6) P(1)
P(hex(co:compress("hello ")), hex(co:flush()))
local o=zlib.compressobj(6) local part = o:compress("abcabcabc")..o:flush() P(hex(part))
local di=zlib.decompressobj() P(di:decompress(part)) P(di:flush()) P(di:close())
P((pcall(di.decompress, di, "x")))
local g=gzip.open("t.gz","wb") g:write("line1\nline2\n42 3.5\n") P(g:close())
g=gzip.open("t.gz","rb") P(g:read("*l"), g:read("*a")) P(g:close()) 
for l in gzip.lines("t.gz") do P("L",l) end
g=gzip.open("t.gz","rb") P(g:seek("set",2), g:read(3), g:seek("cur")) g:close()
P(gzip.open("nonex.gz"))
local h = io.open("t.gz","rb") P(hex(h:read(10))) h:close()
os.remove("t.gz")
P(zip.open and type(zip.open))
P(pcall(zip.open,"nonex.zip"))
P(zip._VERSION, zip._DESCRIPTION and #zip._DESCRIPTION)

