lfs.mkdir("lfs") lfs.chdir("lfs")
local function sorted(t) local k={} for a in pairs(t) do k[#k+1]=tostring(a) end table.sort(k) return table.concat(k,",") end
lfs.mkdir("d1") P(lfs.mkdir("d1"))
P(lfs.mkdir("nonex/a/b"))
local f=io.open("f1.txt","wb") f:write("hello") f:close()
P(lfs.isdir("d1"), lfs.isfile("f1.txt"), lfs.isfile("d1"), lfs.isdir("zzz"))
local a=lfs.attributes("f1.txt") P(a.mode,a.size,a.permissions:sub(1,3),#a.permissions,a.nlink,type(a.modification))
P(lfs.attributes("f1.txt","size"), lfs.attributes("f1.txt","mode"))
P(lfs.attributes("nofile"))
P((pcall(lfs.attributes,"f1.txt","bogus")))
P(lfs.attributes("d1","mode"))
P((pcall(lfs.attributes)))
P(lfs.link("f1.txt","hard"), lfs.link("f1.txt","sym",true))
P(lfs.symlinkattributes("sym","mode"), lfs.symlinkattributes("sym","target"), lfs.attributes("sym","mode"))
P(lfs.readlink and lfs.readlink("sym"))
P(lfs.touch("f1.txt",1000,2000), lfs.attributes("f1.txt","modification"), lfs.attributes("f1.txt","access"))
P(lfs.touch("nof"))
local names={} for n in lfs.dir(".") do names[#names+1]=n end table.sort(names) P(table.concat(names,","))
P((pcall(lfs.dir,"nonexdir")))
local it,dir = lfs.dir("d1") P(type(it)) P(dir:next()) dir:close() P((pcall(dir.next,dir)))
P(lfs.rmdir("d1"), lfs.rmdir("d1"))
P(lfs.currentdir() == lfs.currentdir(), lfs.chdir("nonexd"))
P(lfs.setmode(io.stdout,"binary"))
P(lfs._VERSION, lfs._DESCRIPTION)
P(lfs.mkdirp and lfs.mkdirp("x/y/z"), lfs.isdir("x/y/z"))
P(lfs.shortname and lfs.shortname("f1.txt"))
local l,e = lfs.lock(io.open("f1.txt","r+"),"w") P(type(l),e)
P(lfs.lock_dir("lockd")) P(lfs.lock_dir("lockd"))
local lk = lfs.lock_dir("lockd2") P(type(lk), type(lk) == "table" and sorted(getmetatable(lk) or {}) or "")
P(lfs.unlock(io.open("f1.txt","r+")))
os.remove("sym") os.remove("hard") os.remove("f1.txt")

