[package]
name = "tex-biber"
version.workspace = true
edition.workspace = true
license = "MIT OR Apache-2.0"
description = "Self-contained Rust biblatex bibliography processor"

[dependencies]
tex-kpse = { path = "../tex-kpse", default-features = false }
roxmltree = "0.20"
md5 = { package = "md-5", version = "0.11" }
unicode-normalization = "0.1"
unicode-segmentation = "1"
regex = "1"
